### ISSUE TITLE
select a captive portal interface for the rogue network

### ISSUE THREAD

**Issue by MXRaider** [FluxionNetwork/fluxion#100]
### Do you want to request a *feature* or report a *bug*?
*Bug i think?

### What is the current behavior?
*so far everything perfect but when i get the handshake and i am prompted to select a captive portal interface for the rogue network i see this

[01] *
[02] back

#### If the current behavior is a bug, please provide the steps to reproduce it.
*select a captive portal interface for the rogue network

#### What do you think the expected behavior should be?
I have no idea

**Comment by MPX4132** [comment]
You just need to download the portals/sites. They're not included by default anymore, since it was getting pretty large (file size). 
If you're using git to download the project, download it with submodules (sites):
```
git clone --recursive git@github.com:FluxionNetwork/fluxion.git
```
Otherwise, get them [from here](https://github.com/FluxionNetwork/sites) and put then in `fluxion/attacks/Captive Portal/sites`

**Comment by Geczy** [comment]
Maybe we can add a catch in fluxion to check for sites

**Comment by MXRaider** [comment]
Thanks a lot guys, keep up the awesome and outstanding work!

**Comment by MPX4132** [comment]
Thanks for the feedback.
