### ISSUE TITLE
Helppp? im having a problem with fluxion!!! Everything starts beautiful, even the Fake AP... but when you connect devices to fake AP, Captive portal doesn’t show on the device (phishing page)!

### ISSUE THREAD

**Issue by Dakshkanani** [FluxionNetwork/fluxion#1013]
Helppp? im having a problem with fluxion!!! Everything starts beautiful, even the Fake AP... but when you connect devices to fake AP, Captive portal doesn’t show on the device (phishing page)!

**Comment by cjb900** [comment]
How is anyone supposed to help you with out knowing your set up.
What OS are you using?
are you running said OS in a VM?
What wifi adapter/chipset do you have?
What type of mobile device are you trying to connect to the fake AP?

In my testing everything works. I get the captive portal on my 2 Samsung phones and my iPhone with no issues.

**Comment by Dakshkanani** [comment]
Iam use Linux In Viruatbox
My wifi adaptor Run Perfectly 
My Phone Is Redmi Note 4

Plz Help How Solve This Problem 🙏 And Create Fake Ap Mobile Automatically Disconnected  Fake Ap

**Comment by cjb900** [comment]
well telling me your wifi adapter runs perfectly does not help. Not all wifi adapters are properly supported for evil twin wifi hacking which is what fluxion does. thats why i asked what adapter/chipset you have. Also wifi hacking in a VM is known to be unreliable so its possible using a VM could be part of your issue as well

**Comment by Dakshkanani** [comment]
Wait I will Check

**Comment by Dakshkanani** [comment]
My wifi Chep   MT7601U

**Comment by cjb900** [comment]
so that chipset is a known one that does not properly work for wifi hacking. That is most likely why you are having issue. You are going to need to look into getting a new wifi adapter/chipset that is properly supported. Below is a list of known good adaters/chipsets. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by Dakshkanani** [comment]
I Check Adapter Very Costly Iam Not Affordable Plz Give Me Cheap Price  Adapter

**Comment by cjb900** [comment]
These are the only adapter/chipset that have been tested and properly work. Any adapter you get that doesn't have one of these chipsets no one can guarantee it will probably work. Being from the US the places and prices are going to very widely. So unfortunately you will just have to keep searching for one of these chipsets.

**Comment by Dakshkanani** [comment]
How I Contact u?? U use Any Social Media Platform?? Plz Send me Message

**Comment by Dakshkanani** [comment]
So Fluxion Not Work For me How I can Hack Wifi Different Method Work 100% ??? plz Tell me

**Comment by Dakshkanani** [comment]
Plz Help

**Comment by strasharo** [comment]
Stop the spam or you'll be banned.

**Comment by cjb900** [comment]
@Dakshkanani if you looked on the main github page you would see we have a discord server where you can message us https://discordapp.com/invite/G43gptk
