### ISSUE TITLE
Got struck at starting captive portal

### ISSUE THREAD

**Issue by phoenix-1302** [FluxionNetwork/fluxion#1017]
Hello, I am using jan 2021 version of kali  linux. I have installed the tool fluxion  version 6.9. I have a wireless adapter with driver M7601U that works fine for packet injections. But still when I start the captive portal section it doesn't start for me. It gets stuck at starting captive portal. When I run fluxion with ./fluxion.sh -d it shows the error that the driver mode couldn't be configured. Please help me

**Comment by cjb900** [comment]
if that chipset is actually a MT7601U one, that is known to not properly work. Just because an adapter supports packet injection does not mean it will work for an evil twin attack. It has to support monitor mode, AP mode and VIF. Here is a list of known supported chipsets/adapters 

Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by phoenix-1302** [comment]
Thanks for your reply. The adapter supports monitor mode and during AP mode only, the hostapd config file shows error and I don't have any idea of VIF.

**Comment by cjb900** [comment]
VIP is the ability for an adapter to be able to create a fake AP and deauth at the same time which that adapter does not do. so you will need to either get a second adapter and use 2 adapters with fluxion or replace that adapter with one that is properly supported

**Comment by phoenix-1302** [comment]
Is there any other tool that doesn't create this problem with that chipset?

**Comment by cjb900** [comment]
This is not a problem of the tool. its just that this chipset does not properly support VIF. so any tool that attempts to create a fake AP and deauth at the same time like fluxion is going to not work with this chipset.

**Comment by phoenix-1302** [comment]
@cjb900 thanks for your assistance brother if there are any other usb wifi adapters that would support the AP MODE and VIF  other than those mentioned above, please mention them down

**Comment by cjb900** [comment]
these are the only adapters/chipsets that have been tested and known to work 100%. There may be others out there that have not been tested that may work but no way to know 100%. So if its not in the list above you would need to find someone or something online that is able to verify that it will work and support all the needed modes.

**Comment by phoenix-1302** [comment]
Tplink WN722N v3  is available will it be okay

**Comment by cjb900** [comment]
if it does not have one of the chipsets above it is not recommended to get it as there is no way to guarantee it will work. But the chipset in that adapter is a known one that does not support VIF so would not work on its own. Only the V1 of that adapter has a chipset that is compatible and TP-Link no longer makes the V1

**Comment by phoenix-1302** [comment]
![IMG_20210207_145717.jpg](https://user-images.githubusercontent.com/78671668/107142414-c9476200-6954-11eb-843b-b2cda2f354e4.jpg)
My adapter is able to create an virtual interface. Its the problem with hostapd

**Comment by phoenix-1302** [comment]
Check the photo

**Comment by cjb900** [comment]
creating an AP with hoatapd does not mean that it supports VIF. You are not the only one that has tried to use this chipset and none of them from what i've seen has been able to get it to work in an evil twin attack whether its flixion or some other tool. You are just going to have to get a second adapter with a supported chipset. If you are unable to find one there is no way to get the chipset you have to work at least fro what i've seen from others that have tried.
