### ISSUE TITLE
Hidden network and Fluxion

### ISSUE THREAD

**Issue by Nappy-Says** [FluxionNetwork/fluxion#1024]
Hello developer! 
I have a little problem. 
When I got handshake hidden network confirmation, I also got the name of the network and the users that were connected.
When I try to create an evil twin, Fluxion does not create a captive portal.

Can I fix this by editing fluxion files and how?

**Comment by MPX4132** [comment]
This will not work with fluxion, sorry. The problem is the user must be able to select the target network so they can attempt connecting to the evil twin. Problem is hidden networks can’t really be selected on all devices, so this isn’t much of a limitation with fluxion, it’s more of a limitation with the wireless clients, but we also can’t do a whole lot about it since we’ve got to give the fake AP an SSID. What I’m trying to say is it’s a limitation on multiple fronts that makes adding support for this very much a futile effort.
