### ISSUE TITLE
RTL8812AU+"Unable to initiate network interface attack"

### ISSUE THREAD

**Issue by wolfly22** [FluxionNetwork/fluxion#1054]
I try this soft，but got this:
![fluxion问题](https://user-images.githubusercontent.com/37268959/121618503-749a2c00-ca99-11eb-984a-be8428c8ddbc.jpg)

My wifi_hard is RLT8812au,my system is kali( in VMware)
I  already got the handbag！when i create the evil_twin_ap, i get this :
**Unable to initiate interface attack**

I want to know:Is Fluxion6.9  don't  support  RLT8812au? 
what  should i do  next？
Thanks for help！Fluxion is very  great_wifi_soft!

**Comment by cjb900** [comment]
This is not an issue with fluxion. The issue is that the chipset in the adapter you are using is the issue. RTL chipsets are notoriously problematic for wifi hacking. There is no way to get this adapter/chipset to work by its self in fluxion. You will need to either replace this adapter with one that supports AP mode, Monitor mode, and VIF or get a second adapter to use along with this one with fluxion.
