### ISSUE TITLE
Fluxion for windows 10

### ISSUE THREAD

**Issue by TEJASK111** [FluxionNetwork/fluxion#1056]
Can anyone help me to install fluxion in windows 10 . I m new to kali tools plzz

**Comment by cjb900** [comment]
If you are referring to using the WSL version of Kali in windows 10. This will not work due to the underlining permissions missing for properly controlling a WiFi adapter for WiFi hacking. There is no way to get fluxion to work in WSL. If you are using Kali in a VM in windows 10 you can easily follow the instructions on the github page for fluxion.
