### ISSUE TITLE
unable to start captive portal interface in fuxion

### ISSUE THREAD

**Issue by anuragpatil66** [FluxionNetwork/fluxion#1058]
i downloaded fuxion recently. i could successfully get the handshake, but when i was trying to to the evil twin attack, i got unable to start captive portal interface. ppls help me.....

**Comment by anuragpatil66** [comment]
i am using TP-Link Arher  T2U PLUS [RTL8821AU]

**Comment by cjb900** [comment]
@anuragpatil66 the reason you are having issues is that the chipset in that adapter does not support VIF and or AP mode which is needed to properly use fluxion. you would either need to get a new wifi adapter that supports monitor mode, AP mode and VIF or got a second adapter to use with fluxion

**Comment by anuragpatil66** [comment]
@cjb900 can u suggest an adapter which supports these modes

**Comment by cjb900** [comment]
Any of these adapters/chipset will work. Some may require additional set up though. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by sivabala21** [comment]
> @anuragpatil66 the reason you are having issues is that the chipset in that adapter does not support VIF and or AP mode which is needed to properly use fluxion. you would either need to get a new wifi adapter that supports monitor mode, AP mode and VIF or got a second adapter to use with fluxion

In my Case I am using Pi zero W , Built in Wifi works as Monitor Mode , for 2nd Adapter Can I buy this adapter ? 
Only AP Hosting is Problem ryt ? If that case , My PI zero w builtin wifi can do that so ? Crct me If I am wrong !

**Comment by cjb900** [comment]
@sivabala21 Well I don't have a pi zero w or that wifi adapter. So in theory that will work but I can't say 100%. But personally I would recommend getting an adapter with a known good chipset. RTL chipsets are notoriously problematic for wifi hacking.

**Comment by sivabala21** [comment]
@cjb900 Thanks for the reply! Actually, there is an issue with buying the chipset you mentioned in my country. Most of the time, it’s either unavailable or extremely overpriced. The adapter I mentioned is one of the few affordable options available for people here to explore these techniques, which is why there’s so much interest in it.

Apart from that, I have a doubt. Nowadays, routers mostly operate on 5GHz, so 2.4GHz cannot deauth all the 5GHz clients, right? In that case, my Pi Zero W won’t be able to deauth, correct me if I’m wrong.

If that’s true, I’ll need to buy another Archer T2U adapter. One can be used for deauthing 5GHz, and the other as an AP host. I understand that it doesn’t support VIP, which means I’ll need two adapters. However, buying the chipset you mentioned is much more expensive than this option .

**Comment by cjb900** [comment]
2 things here. One you don't have to buy the exact adapters from that list. Just what ever wifi adapter you get needs a known supported chipset in it. Second when deauthing you can only deauth 2.4ghz with 2.4Ghz and 5ghz with 5ghz. Meaning you can not deauth 5ghz with only a 2.4Ghz capable wifi adapter/chipset.
