### ISSUE TITLE
Driver Implementation

### ISSUE THREAD

**Issue by throwawaya609** [FluxionNetwork/fluxion#1105]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Implement realtek8112bu driver please
(it works with Linux + Wifite + deauth capability etc)

**Comment by cjb900** [comment]
Drivers for any wifi chipset are not controlled by fluxion. They are controlled by the Linux kernel or distro you are using. If you can not get it to work in fluxion that is most likely because it is an RTL chipset and those can be notoriously problematic for wifi hacking. You can try running ``sudo airmon-ng check kill`` before starting fluxion and see if that helps any. If not you will most likely have to look at getting a better more supported wifi adapter/chipset if you want to use fluxion. Below is a list of known good adapters.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
