### ISSUE TITLE
since 2020 I have written to receive support nobody helps me !!!

### ISSUE THREAD

**Issue by xm00ds** [FluxionNetwork/fluxion#1111]
I need to know where I put the script so that my fluxion ignores wlan0 because I connect to that device by ssh or vnc, I need it to only use wlan1

I have an old version of fluxion but, I really don't know why when starting it kills the 2 wlan0 and wlan1 to be able to start the monitor mode I need to know how I should configure it so that the program doesn't touch the wlan0

**Comment by xm00ds** [comment]
After I select wlan1, it kills the 2 wlans, both 0 and 1, and I lose connection with the device, how can I configure it so that fluxion doesn't even see that there is a wlan0, and this way I don't lose connection

**Comment by cjb900** [comment]
If you would check your issue from 2020 was closed because you did not use the issue template which clearly states "Note: All issues will instant closed if the issue template is not complete. Please understand that it is easier for us if you fill out the template to help you faster." 

Also if you are using an old version of fluxion its possible its running something like ``airmon-ng check kill`` which would kill any open internet connection. It would be recommended to either use an Ethernet cable and not wlan0 or just not use ssh/vnc to access your device since wifi hacking is going to cause issues with any wifi interface you are using.

But since you didn't fill out the issue template this issue is getting closed.
