### ISSUE TITLE
Unable to start captive portal interface, returning!

### ISSUE THREAD

**Issue by dkuznetsov21** [FluxionNetwork/fluxion#1129]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question
After get a handshake i can't create "evil twin"
<img width="855" alt="image" src="https://user-images.githubusercontent.com/42741535/214029978-a52c9b2d-2326-425f-86b4-ca559a8da9f2.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/42741535/214035297-65ff28b8-6455-40f3-9fd5-c44153999683.png">

#### Specs
Kali in virtualBox
Adapter - TP-Link Archer T2U PLUS [RTL8821AU]

**Comment by cjb900** [comment]
Well your issue is that the chipset in your wifi adapter is a crap RTL one and does not support AP/VLAN (aka VIF). There is no fix for this either. VIF is the ability for the card split into 2 virtual interfaces so it can create the fake AP and deauth at the same time. You will need to either get a second card to use 2 in fluxion (one for deauthing and one for creating the fake AP) or ditch that card all together and get a better supported one. Below is a list of supported cards/chipsets. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
