### ISSUE TITLE
Captive portal options missing.

### ISSUE THREAD

**Issue by 2009h** [FluxionNetwork/fluxion#113]
![capture d ecran1](https://user-images.githubusercontent.com/20770325/29578930-68cfedc0-8771-11e7-851f-8016d8e76c9c.png)
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh`*

**Comment by MPX4132** [comment]
You just need to download the portals/sites. They're not included by default anymore, since it was getting pretty large (file size). 
If you're using git to download the project, download it with submodules (sites):
```
git clone --recursive git@github.com:FluxionNetwork/fluxion.git
```
Otherwise, get them [from here](https://github.com/FluxionNetwork/sites) and put then in `fluxion/attacks/Captive Portal/sites` 
Once you've downloaded them and you see them available, come back here and lets us know so we can close the issue.

**Comment by MPX4132** [comment]
Make sure to get the latest version from the repository. It includes the generic sites by default now.

**Comment by deltaxflux** [comment]
I turn on my GitHub bot which auto reply to such messages.

**Comment by MPX4132** [comment]
Oh ok, thanks, that should help.

**Comment by 2009h** [comment]
Thank you very much that it works
