### ISSUE TITLE
Unable to start captive portal interface error. Please help

### ISSUE THREAD

**Issue by Adamo89** [FluxionNetwork/fluxion#1139]
|    Q        |   A
|------------ | -----
| Version     | 6.11

#### Support Question
I am able to to use the handshake snooper to deauth and collect a handshake but when I attempt to run the captive portal attack it gives me an error when selecting the interface for the access point. It says "Unable to start captive portal interface, returning!" I have also attached a screenshot of the error and the supported interface modes for my wifi adapter. Thanks!

#### FLUXION Info
FLUXION V6.11

#### BASH Info 
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** rtl88XXau
**Chipset:** Realtek Semiconductor Corp. Realtek 8812AU/8821AU 802.11ac WLAN Adapter [USB Wireless Dual-Band Adapter 2.4/5Ghz]
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(378)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.10
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2022, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.7  - (C) 2006-2022 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                                                     

#### System Info
**Chipset:** Linux version 6.0.0-kali6-amd64 (devel@kali.org) (gcc-12 (Debian 12.2.0-10) 12.2.0, GNU ld (GNU Binutils for Debian) 2.39.50.20221208) #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19)

#### Chipset
Chipset: 88XXau
Chipset is not in list

![Error for captive protal](https://user-images.githubusercontent.com/109393227/219905588-3722ec00-6ee1-44d9-ab3b-8961327603da.jpg)

![Wifi adapter interfaces](https://user-images.githubusercontent.com/109393227/219905585-7e37ff1e-010d-410a-9770-1f17320bb7a5.jpg)

**Comment by cjb900** [comment]
Your issue is that chipset does not support VIF (shows as AP/VLAN). VIF is what allows the chipset to split into 2 virtual interfaces. One to deauth the AP you are attacking and one to create the fake AP. There isn't any way to give your wifi adapter VIF support as its a hardware limitation of the chipset. You will either have to get a second wifi adapter to use 2 in fluxion or ditch that on all together and get a supported on from the list below. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by Adamo89** [comment]
I just found another closed ticket with the same issue. Thanks for the help. Its what i deserve for trying to be a bit cheap.

**Comment by Adamo89** [comment]
Hi again! So i got a new adapter, went with the Panda PAU09 RT5572. It appears like everything is working fine. I can see the rt2800usb driver and it shows up with an iwconfig. Its not until I run the Handshake Snooper that I run into problems. fluxion takes over the wlan0 but when running the attack it does not return any networks.

**Comment by Adamo89** [comment]
Resolved the issue. Used airmon-ng and put the device into monitor mode. I can see all the networks now.
