### ISSUE TITLE
not installing in parrot os

### ISSUE THREAD

**Issue by Adarshthakut** [FluxionNetwork/fluxion#1186]
./fluxion.sh: line 255: format_center_literals: command not found

./fluxion.sh: line 262: format_center_literals: command not found

./fluxion.sh: line 270: installer_utils_check_update: command not found

./fluxion.sh: line 289: installer_utils_check_dependencies: command not found
./fluxion.sh: line 290: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**i am using offical version**
cat /etc/os-release
PRETTY_NAME="Parrot Security 6.0 (lorikeet)"
NAME="Parrot Security"
VERSION_ID="6.0"
VERSION="6.0 (lorikeet)"
VERSION_CODENAME=lory
ID=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://www.parrotsec.org/community/"
BUG_REPORT_URL="https://gitlab.com/parrotsec/"

**Comment by cjb900** [comment]
Creating multiple issues for this is not going to get us to help. Also, I just created a new install of Parrot OS HTB edition and fluxion is working just fine here. So as I have said more than once this is something on your end and not an issue with fluxion. So you will need to fix this on your own since this is not reproducible here.
![image](https://github.com/FluxionNetwork/fluxion/assets/47070308/851ef586-a9dc-464c-b5cf-0aeec0937783)
![image](https://github.com/FluxionNetwork/fluxion/assets/47070308/140fa534-ec4f-4f92-883c-f1163de1dca6)

**Comment by Adarshthakut** [comment]
Another option
Please help

**Comment by cjb900** [comment]
If you can't figure out how to fix this then you should not be trying to hack wifi and should start by learning Linux basics.
