### ISSUE TITLE
Minor bugs.

### ISSUE THREAD

**Issue by usmarine2141** [FluxionNetwork/fluxion#122]
### Do you want to request a *feature* or report a *bug*?
*Bug*

BUG

### What is the current behaviour?
When no client is connected it still shows a conntection but other windows say nobody is connected, Also it does not report as in ver 2 in the authenticator window

#### If the current behaviour is a bug, please provide the steps to reproduce it.
start AP, connect, it does not show the client, then it still says there is a client connected yet there isnt. 

#### What do you think the expected behaviour should be?
should show 0 if no client is connected. 
should show the clients online like in previous version. 

### Specs
n/a

NOTE: To update do we just re git clone? or is there a file included to update?

**Comment by usmarine2141** [comment]
also not entirely sure the deauth is continuing to work once the fake AP is up, not sure how i can validate that, but i should have more clients connecting i would assume.

**Comment by MPX4132** [comment]
If you do not have the latest version (fluxion v3.2), I suggest you reclone with
```
git clone --recursive git@github.com:FluxionNetwork/fluxion.git
```
The version change (from v2 to v3) might've broken the old updater.
If you do **not** have the latest version, the bugs you mentioned are probably no longer relevant.

I can't tell what you have because you didn't run the diagnostics script.

**Comment by MPX4132** [comment]
No response after a few days, I'm closing this.
