### ISSUE TITLE
*Request* ./fluxion.sh -captive [interface] 

### ISSUE THREAD

**Issue by JoinFreeMe** [FluxionNetwork/fluxion#134]
*feature*

### What is the current behaviour?
*Checks if any devices are monitor mode compatible & if export is active, else exits *

#### Proposed feature
*ability to add a flag or menu option(at start) to ./fluxion.sh that allows a skip to the Captive Portal without use of any monitor mode devices*

### Specs
*raspberry pi 3* 
nexmon to enable monitor mode (https://github.com/seemoo-lab/nexmon)
x1 unsupported wireless adapter (no monitor mode)

**Comment by MPX4132** [comment]
I don't think it's possible to abandon monitor mode completely. The script sets interfaces in monitor mode to "reserve" them. It might be possible but we would need to find an alternative and I've been having less time to work on the script lately, so it might take a while to even check whether it's feasible to do something else.

Your idea of having a CLI offering script parameters is pretty neat, so that one's fairly doable.

**Comment by deltaxflux** [comment]
I would prefer to use a local variable.
Like:
`export Interface=wlan0`

**Comment by deltaxflux** [comment]
No response closing.
