### ISSUE TITLE
Problem capture handshake

### ISSUE THREAD

**Issue by burton19** [FluxionNetwork/fluxion#140]
Hi everyone, I hope someone could help me.
I use fluxion on my raspberry pi 3 with kali arm as OS, I have a problem when I try to capture the handshake. When I use aircrack and then I launch the command "deauth all" the windows that show the ssid and the captured handshake close itself automatically, the advise showed is Network is down.
Same thing with the "deauth all (mdk3)".

The only way to capture the handshake is using pyrit with "deauth all (mdk3), but when I try to launch the attack I have an advise that tells me "failed to set beacon parameters".

I think all my settings are good enough to use fluxion, but I hope to find someone who could help me.

**Comment by deltaxflux** [comment]
Run
`sh scripts/diagnostics.sh [interface]`

**Comment by burton19** [comment]
I am sorry, I can`t open that command.

root@kali:~/Desktop/fluxion-master# sh scripts/diagnostics.sh
sh: 0: Can't open scripts/diagnostics.sh
root@kali:~/Desktop/fluxion-master# cd ..
root@kali:~/Desktop# cd ..
root@kali:~# sh scripts/diagnostics.sh
sh: 0: Can't open scripts/diagnostics.sh
root@kali:~# 

Maybe I run the wrong command in the wrong directory.

**Comment by burton19** [comment]
This is the result. Maybe I wrote something wrong.

root@kali:~/fluxion# sh scripts/diagnostics.sh [wlan1]
scripts/diagnostics.sh: 3: scripts/diagnostics.sh: source: not found
[ FLUXION Info ]
scripts/diagnostics.sh: 10: scripts/diagnostics.sh: Syntax error: "(" unexpected

**Comment by MPX4132** [comment]
Just like you did before, go into the Fluxion directory and run it like this:
```
./scripts/diagnostics.sh wlan1
```

**Comment by burton19** [comment]
This is what I have:

root@kali:~/fluxion# ./scripts/diagnostics.sh wlan1
[ FLUXION Info ]
FLUXION V3.2


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy17
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: ioctl(SIOCGIFINDEX) failed: No such device
failed


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.4.50-v7 (root@builder) (gcc version 4.8.3 20140401 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.04 - Linaro GCC 4.8-2014.04) ) #1 SMP Fri Apr 21 01:18:29 CDT 2017

I did the diagnostic on my interface with Alfa AWUS036NHA

**Comment by deltaxflux** [comment]
Your card isn't suitable for injection.

**Comment by burton19** [comment]
Thank you very much for your help! Could you suggest me if I need to change my Alfa with a model more powerful?

**Comment by deltaxflux** [comment]
Well I rode in the forum your card is suitable with a small patch [here](https://ubuntuforums.org/showthread.php?t=1767143)

**Comment by MPX4132** [comment]
@burton19 I've been using two cards with the same driver as yours, meaning, your card should be supported without anything else. HOWEVER, I suspect there might be a mechanical issue with it. For example, it looks like it has been disconnected multiple times by the fact your computer assigned it "phy17" instead of phy0 or phy1... I think your card is disconnecting.

**Comment by burton19** [comment]
@MPX4132 I saw that my connection with my Alfa awus036nha was not stable! Despite the Broadcom in my raspberry pi 3 is stable, I noticed that multiple time Alfa card disconnects and reconnects, so I will try to solve this problems adding drivers of atheros cause I see that the card is an ath9k_htc and I found the drivers!

Please feel free to correct me if I said something wrong!

**Comment by MPX4132** [comment]
Actually, I run fluxion on an older Raspberry Pi B+ which I use to test with. I had to splice a USB cable to get the power from an external source, rather than the Raspberry Pi. The external source is a (USB) phone charger to power the Alfa, but kept the data cables connected to the Raspberry Pi. Basically, I made a Y cable, similar to [this one](https://sgcdn.startech.com/005329/media/products/gallery_large/USB2HAUBYX.main.jpg). Since I made mine, it looks a bit ghetto with the electrical tape lol, but it works fine.

**Comment by burton19** [comment]
Sounds good your advices! I try before with the download of the drivers and I ll let you know, if the connection is not stable... If the problem persist I will buy an adapter to connect Alfa to rasp for the connection and the phone charger to Alfa for the power

**Comment by MPX4132** [comment]
@burton19 All you would need to get is a "powered usb hub," just look one up. Something like [this one](https://www.amazon.com/AmazonBasics-Port-2-5A-power-adapter/dp/B00DQFGH80), but it can be any other that has external power supplied to the hub.

**Comment by burton19** [comment]
@MPX4132 you were right, the problem was my Alfa had less power, so I bought an usb hub with charger and I tried on my own network and it worked! Thank you for your support and for helped me!

**Comment by MPX4132** [comment]
@burton19 Awesome news, thanks for reporting what you found out.

**Comment by deltaxflux** [comment]
I never thought about power issues but it is solved.

**Comment by MPX4132** [comment]
@deltaxflux It's a common problem when dealing with the Raspberry Pi. I just jumped to that conclusion since I've had experience with that same problem.

**Comment by deltaxflux** [comment]
Well, I have a Raspberry b+ ,2 and 3 but I use everytime a powered USB hub so I don't have to deal with power management.

**Comment by MPX4132** [comment]
I never bought one since I never used all the USB ports. I configured the Pi B+ as a headless server, and the only thing hooked up to it, other than power, is the ethernet cable and a USB wifi adapter, to have wireless capabilities if I ever need them for anything. I just spliced two usb cables I had laying around and pulled the power line (assuring common ground) to another USB A interface, then plugged that into a USB wall adapter, lol. A bit ghetto but it works perfectly fine.
