### ISSUE TITLE
fix bug xterm handshake Snopper

### ISSUE THREAD

**Issue by SiNaPsEr0x** [FluxionNetwork/fluxion#148]
fix dont close window after attack.. 
<img width="1386" alt="schermata 2017-09-09 alle 16 39 00" src="https://user-images.githubusercontent.com/5438823/30241129-b1201644-957d-11e7-9d6e-c69f1eee8428.png">

**Comment by MPX4132** [comment]
I don’t think this should be fixed. I purposely leave the window open to signify nothing crashed.

**Comment by deltaxflux** [comment]
Well, I would prefer that we close the window but we should also create a new window which says:" Handshake found" or something. What do you think @MPX4132 ?

**Comment by SiNaPsEr0x** [comment]
Yes prefer this mode

**Comment by MPX4132** [comment]
@deltaxflux I definitely agree with that. Maybe we could have xterm execute something after airodump-ng finishes execution, like an echo with “success” or “failure”, depending on the existence of the cap file (success if generated, failure otherwise). The simpler the answer, the better, at least that’s what I think.

**Comment by deltaxflux** [comment]
It's implemented now, check it out and share your opinion about that.
