### ISSUE TITLE
Fluxion is not capturing the handshake

### ISSUE THREAD

**Issue by usherfiles** [FluxionNetwork/fluxion#165]
### Do you want to request a *feature* or report a *bug*?
*Bug*
Fluxion doesn't capture the handshake with the Pyrit verification

### What is the current behaviour?
*fluxion crashes*
Every time I try to capture the handshake with pyrit , the handshake is captured but the "UI for handshake" keeps going and going... but when I capture the handshake with the other method (I can't remember the name right now and I'm not at home to check it ) It successfully captures it and closes all the windows, and then when I try to start the attack with pyrit and with that handshake, fluxion says invalid hash file, But I can't capture the handshake with pyrit because the attack (mk3) just keeps going and going, it doesn't stop even it already has de handshake ( I tried leaving home from an hour) 
#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*
Open fluxion, select a SSID, try to capture the handshake with pyrit, and that's it for me
here is fluxion capturing the handshake after it already has it... that windows kept opened for an hour like that 
![captura](https://user-images.githubusercontent.com/8587998/30407555-2818a258-98cf-11e7-8390-abbf9ae09e56.JPG)

#### What do you think the expected behaviour should be?
*What do you think should happen?*
I think it should close al the "capturing handshake" windows 
### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Im not at home right now :(

PS: Sorry if my info is a little "noob" for you... I'm a little new to Fluxion 3 (I was using fluxion 0.44 on wifislax until I saw the repo for fluxion3)

**Comment by deltaxflux** [comment]
First of all, you should not use mdk3. It is too aggressive instead use aireplay-ng. Secondly, we should check if you have installed the python lib scapy. Use the following command:
`pip2 freeze | grep scapy`<br>
**Sample output:**
scapy===unknown.version
scapy-python3==0.21

If you don't see any output there you have to install the scapy lib
`pip2 install scapy`

We have to use python2 because the fake DNS script is only for python2. Meanwhile, I would recommend that you turn on the debug mode and check the log.
`export FLUXIONDebug=1`

If you have any trouble let me know.

**Comment by deltaxflux** [comment]
Closing:

Reason: **No response**
