### ISSUE TITLE
interface wlanx down error 

### ISSUE THREAD

**Issue by calee4nyaboy** [FluxionNetwork/fluxion#172]
Environment: latest kali, fluxion 3.3, both RTL8187 & ath5k cards. 

I am running the handshake utility on either card listed above but after a few minutes the deauth window in the lower right corner disappears and the handshake window in the upper right corner gives the error: interface wlanx down.  Not sure why this is happening. 

Any guidance would be appreciated. Thanks!

**Comment by calee4nyaboy** [comment]
![20170918_162530](https://user-images.githubusercontent.com/31833255/30575040-d6604d48-9cb2-11e7-94cb-ffcbe62c06ff.jpg)

**Comment by deltaxflux** [comment]
Run the diagnostic script.

**Comment by calee4nyaboy** [comment]
I ran the diag for both of the interfaces and will copy them separately below

**Comment by calee4nyaboy** [comment]
[ FLUXION Info ]
FLUXION V3.3


[ BASH Info ]
GNU bash, version 4.4.11(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy1
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(327)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.9.0-kali3-686-pae (devel@kali.org) (gcc version 6.3.0 20170321 (Debian 6.3.0-11) ) #1 SMP Debian 4.9.18-1kali1 (2017-04-04)

**Comment by calee4nyaboy** [comment]
[ FLUXION Info ]
FLUXION V3.3


[ BASH Info ]
GNU bash, version 4.4.11(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy0
Driver: ath5k
Chipset: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter (PCI-Express) (rev 01)
Injection Test: No Answer...
Injection is working!


[ XTerm Info ]
Version: XTerm(327)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.9.0-kali3-686-pae (devel@kali.org) (gcc version 6.3.0 20170321 (Debian 6.3.0-11) ) #1 SMP Debian 4.9.18-1kali1 (2017-04-04)

**Comment by calee4nyaboy** [comment]
Let me know if there is any other info you need or tests I can run.  Thanks for your effort on this app and your support!

**Comment by deltaxflux** [comment]
Sorry for the delay.

**Comment by calee4nyaboy** [comment]
If this is a duplicate, it would be helpful if the person closing it as "duplicate" to say what the original ticket number is that this is supposed to be duplicating. I have no idea what "master ticket" this should point to.

Furthermore, if this is a current issue, then it seems to me the master ticket should still be an open ticket but I don't see any open ticket that talks about this "interface wlan down"  problem.

**Comment by deltaxflux** [comment]
I labelled the wrong issue.

**Comment by calee4nyaboy** [comment]
Thanks for reopening. An interesting point about this issue is that it occurs on two very different cards. At first I thought it might be a driver issue but I don't think it is.

**Comment by usama7628674** [comment]
@calee4nyaboy 
Try using USB hub.Maybe your USB ports are not providing necessary current.

**Comment by MPX4132** [comment]
You said they’re both using the same driver. It’s very likely it is in fact the driver.

**Comment by calee4nyaboy** [comment]
@usama It's not insufficient power as one of the interfaces is on board. By the way, did you get my email? 

@mpx, I didn't say they were using the same drivers. I actually said the exact opposite and listed both of the different drivers that are being used. I even ran the diags separately for each card because the drivers are different. Did you read from the top of the thread?

**Comment by MPX4132** [comment]
@calee4nyaboy did you read what [you wrote yourself](https://imgur.com/a/eE1gs)?

**Comment by calee4nyaboy** [comment]
That means it's happening on 'both' cards. But somebody who understands the mechanics of how these things work, better than myself, knows that after reading that statement that both of those cards use different drivers anyway.  In fact, it is implicit in that statement that it is two different drivers because they are both listed in the statement, the RTL8187 and the ath5k which clearly and obviously do not use the same driver. Not sure how that could possibly be construed as anything other than two different drivers.

**Comment by deltaxflux** [comment]
Well @MPX4132 he uses two different cards meaning two different drivers.

 However the PCI express card **(ath5k )** should work. Do you have the same results with both cards? The other wireless card **(RTL8187)** has not only issues with monitor mode also as far as I can tell there are also incompatibilities with the master mode. We can check this with the following command: <br>
**Monitor Mode:**
`sudo iwconfig wlanX mode monitor`
**Master Mode:**
`sudo iwconfig wlanX mode master`

In general, this problem relates to driver issues, not with an incompatible version of fluxion. You have to figure out on your own because it is not a real bug.

**Comment by MPX4132** [comment]
@calee4nyaboy @deltaxflux Oh, I see, I confused the `RTL8187` for a chipset, but it seems that’s also a driver. My bad.

**Comment by calee4nyaboy** [comment]
@delta: You asked if I'm having this problem on both cards and it says in the description above that I am having it on both cards. That is why I posted the diags for both devices. This issue should not be closed. Have you never seen this issue before with  Fluxion. As for the rtl8187, I have no other problems with it other than it does not support hostapd. Please reopen this ticket

**Comment by deltaxflux** [comment]
Miss the line I wrote: **"You have to figure out on your own because it is not a real bug"**

**Comment by calee4nyaboy** [comment]
A perfectly functioning system on the latest Kali and the latest fluxion with two different drivers are reproducing this error. Seems like a bug to me. You did not answer my question: have you not seen this error in the past anytime? This has never been reported before?

**Comment by MPX4132** [comment]
@calee4nyaboy Sorry man, I just read the entire thread to make sure I got all the information down. I apologize for jumping to conclusions prematurely, but I wasn’t understanding what you were saying originally. Anyway, I’m fairly positive you’re having an issue with conflicting processes. Why do I think that? Well, multiple reasons. The first one is that you’re using an interface for monitor mode which follows the naming convention used by network-manager... that’s a massive red flag. Essentially, chances are network-manager is snatching the interface from fluxion and putting it back into managed mode (interrupting monitor mode). You can run Fluxion with the killer flag to attempt to correct this issue:

```
FLUXIONWIKillProcesses=1; ./fluxion.sh
```

However, it may be more, uh, graceful if you just stopped it yourself:
```
systemctl stop network-manager
```
Then just start it when you’re done by replacing `stop` with `start`. Please report your results here.

P.s there’s also the airmon-ng flag, which uses airmon-ng to set the interface up. You can look for it in the wiki, I forgot what it was. If you use that one, you probabaly wont have to stop network-manager, since airmon-ng changes the interface identifier, making it incompatible with network-manager.

**Comment by calee4nyaboy** [comment]
Thanks for the input! I'll test all this out and report back!

**Comment by jops1984** [comment]
I got same issue, interface wlan0 down error.
I manage to fix by doing:
kill processes `airmon-ng check kill yourprocesses`
it work for me.

**Comment by MPX4132** [comment]
@jops1984 Fluxion can do the killing, if you use the killer flag: 
```
FLUXIONWIKillProcesses=1; ./fluxion.sh
```
You can also save it to your preferences file so that it always kills the processes interfering, however, I advice against killing anything. You should try stopping the service, or services using the interface so you have no issues. If you're on a debian machine, or derivatives like ubuntu and kali, the process that's interfering might be `network-manager`. To stop it, do:
```
systemctl stop network-manager.service
```
or using sudo:
```
sudo systemctl stop network-manager.service
```
