### ISSUE TITLE
Handshake goes forever

### ISSUE THREAD

**Issue by Geczy** [FluxionNetwork/fluxion#175]
Handshake always hangs on this window and never actually captures one. Notice 4 hours elapsed!! 

![image](https://user-images.githubusercontent.com/1036968/30667230-e105d5e2-9e24-11e7-84f2-a691a8b64ffa.png)

**Comment by Geczy** [comment]
This was capture option 1. Trying again with option 2 that deauths ....

**Comment by Geczy** [comment]
The deauth screen disappears after a certain short time then I am left with just the other screens again ...As if it stopped deauthing?

**Comment by deltaxflux** [comment]
Well, I will check.

**Comment by deltaxflux** [comment]
I posted this in #165:
First of all, you should not use mdk3. It is too aggressive instead use aireplay-ng. Secondly, we should check if you have installed the python lib scapy. Use the following command:
`pip2 freeze | grep scapy`<br>
**Sample output:**
scapy===unknown.version
scapy-python3==0.21

If you don't see any output there you have to install the scapy lib
`pip2 install scapy`

We have to use python2 because the fake DNS script is only for python2. Meanwhile, I would recommend that you turn on the debug mode and check the log.
`export FLUXIONDebug=1`

If you have any trouble let me know.

**Comment by EOS123** [comment]
I can't catch any useful information in 12 hours

**Comment by MPX4132** [comment]
@EOS123 Make sure to use aireplay-ng or passive mode, mdk3 is too aggressive. If you've got that down, chances are your target AP has no clients.

**Comment by Geczy** [comment]
I recommend doing what https://github.com/v1s1t0r1sh3r3/airgeddon or https://github.com/derv82/wifite2 does, where it shows the handshake window and if it doesn't find a handshake it 20 seconds, it asks if you want to retry. Then it sends deauth again and waits again. Repeat

**Comment by Geczy** [comment]
It also shows which APs have active clients when selecting an AP, which can be a very useful feature to find which you want to target for handshakes

**Comment by deltaxflux** [comment]
> It also shows which APs have active clients when selecting an AP, which can be a very useful feature to find which you want to target for handshakes

It does that already.

> where it shows the handshake window and if it doesn't find a handshake it 20 seconds, it asks if you want to retry. Then it sends deauth again and waits again. Repeat

Well If you want to want to run it for a while you don't want to input every time.

**Comment by MPX4132** [comment]
Yeah, that's what I think as well. Having to get user input every 20 seconds is terrible. It's better to set it and forget it, so the script is sure to catch something sometime.
