### ISSUE TITLE
Upgrading USB dongle for modern versions of Fluxion

### ISSUE THREAD

**Issue by calee4nyaboy** [FluxionNetwork/fluxion#176]
As I learned a week or so ago, my old RTL8187 wont work on modern versions of Fluxion due to it not supporting current versions of hostapd.  (Wont start the Evil Twin)  Looks like its time to retire the old thing.  Others are in my shoes still using the RTL8187 chipset and was hoping a thread could be created for users looking to upgrade their old equipment so they could enjoy Fluxion to it's full extent.

In my search, I found this card which uses the RT5572 chipset:

http://www.wirelesshack.org/review-panda-wireless-pau09-n600-dual-band-wifi-dongle.html

It is said to support both monitor mode and injection.  Hope theres no other issue with hostapd or some other randomness.  Does anybody have any experience with this chipset?  Was wondering if MPX or Delta had any comments on it.  Thanks!

**Comment by deltaxflux** [comment]
Well, I don't check this issue yet. Meaning that I don't have time to luck at this problem. I personal use the **awus036nh** and it works flawlessly. 

I don't have any experience with the **RT5572** chipset so I can't share any results. Anyway, good luck with your card hope it works.

**Comment by calee4nyaboy** [comment]
I don't have the card. I just found out about it and was wondering what, if anything, other users knew about it.

**Comment by usama7628674** [comment]
You should buy Alfa awus036nh or awus036nha.These two will work flawlessly and you won't face any problem in the future dealing with scripts.I personally use **awus036nha** and it's doing fine for me and I hope for you as well if you get one.

**Comment by ozitrance** [comment]
I actually have this device and just tested it for you with kali on a rpi3 and I'm very happy I did! I'm trying to focus on 5g networks since everywhere I go people only use those networks now and I honestly forgot it was 5g capable.. It uses the rt2800usb which for me always worked great. I was able to catch a handshake from a 5g network in less than 5 seconds! It also works flawlessly with the fake ap attack - something my alfa awus1900 has problems with (or more specifically with the virtual interface operation - it can still do everything but drivers are more buggy). 

In overall, although I really can't talk about anything long term, I'm very impressed so far and very happy you asked about it! :+1: 

In general I think we should start giving more attention to 5g... My experience is very good with those products, they can do anything with both bands and it's really not as as it used to be. I also change the fake ap to use the n band. Not sure if it helps to 'fool' devices or anything but I only see n band networks around me and that b hostapd creates by default looks really different in scans I do with other apps. Might be another feature worth spending time on?

Let me know if you have more questions about  the pau09.

**Comment by calee4nyaboy** [comment]
Thank you so much for your input!  It was exactly what I was looking for! Helps me narrow down my decision on a new device cuz this old alfa's gotta go.

**Comment by MPX4132** [comment]
I've been using the `awus036nha` as well, it's pretty good and stable. The awus036nha uses the `ath9k_htc` driver. I've also had success with the `ath9k` driver, so those two are pretty stable and are fully supported.

**Comment by usama7628674** [comment]
@deltaxflux Awus036nh comes with 2W output power.This means you can increase tx power to 33dbm (2W).Does your adapter go above 20dbm or is it hard locked?

**Comment by calee4nyaboy** [comment]
The FCC in the United States only allows a *maximum* of ONE watt output of *any* WiFi device whether it is a USB dongle or an access point. Any device claiming more than one Watt is a complete and total lie. This is well-known so you can Google it if you want to

**Comment by usama7628674** [comment]
@calee4nyaboy So it means it can go to 30dbm which is 1W.Is that true?

**Comment by calee4nyaboy** [comment]
All I know is the FCC limits all wifi to 1 watt. And most products don't put out anything near 1 watt. It's usually a couple hundred milliwatts at the most. I have been building custom WiFi antennas for a very long time and have looked into this matter.  Products shipped elsewhere in the world most likely also follow this guideline

**Comment by strasharo** [comment]
@ozitrance Is it able to inject as well?

**Comment by calee4nyaboy** [comment]
It? What is it?

**Comment by ozitrance** [comment]
@strasharo if you are asking about the PAU09 so the answer is definitely yes!

**Comment by zq16777** [comment]
The specified path [*] captured shook Bao Cunfang's (for example: /dump-01.cap /...)
The absolute path stored after the handshake bag is caught:
(No matter what the storage path is
The Hash file does not exist!
What can I do to continue the next operation?）

[*] 指定捕获到的握手包存放的路径 (例如: /.../dump-01.cap)

捕获到握手包后存放的绝对路径: ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by zq16777** [comment]
Hello, developer and for WIFI signal SSID hidden no way to create a SSID hidden twin brother AP signal names, only display x0x0x0x0x0x with WiFi signal is not the same name hiding, need to develop a new Fluxion tool!!!!

**Comment by zq16777** [comment]
[*] 指定捕获到的握手包存放的路径 (例如: /.../dump-01.cap)

捕获到握手包后存放的绝对路径: '/root/Desktop/cap' pip-01.cap
[*] Hash文件不存在!

**Comment by Boosted240** [comment]
Give the AWUS052NH a look.  I'm using it with an RPi-3 and love it.

**Comment by calee4nyaboy** [comment]
I ordered the pau09 so it's on its way. We'll see how she runs.  Can always get a different card if it's not to my liking. ☺

**Comment by aqeel5user** [comment]
awus036h working smoothly in wifphisher. try it.
