### ISSUE TITLE
Stuck on "[*] Starting Captive Portal access point service..."

### ISSUE THREAD

**Issue by N1kRolexx** [FluxionNetwork/fluxion#212]
Trying to perform captive portal attack. Fluxion gets stuck on [*] Starting Captive Portal access point service...
And nothing happens after. 

Report: (interface is alfa awus036h rtl8187)
[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171010 (Debian 6.4.0-8)) #1 SMP Debian 4.13.4-2kali1 (2017-10-16)

**Comment by N1kRolexx** [comment]
Also, i choose "Create an SSL certificate", also tried different language options, the result is same.

**Comment by N1kRolexx** [comment]
Well, a minute ago it started to work. I will try some more times to find the reason it didnt want to work :)

**Comment by N1kRolexx** [comment]
Captive portal attack doesnt work with ALFA AWUS036H, it gets stuck on [*] Starting Captive Portal access point service. But it works on Atheros AR9271 chipset. Maybe you should check this out, because a lot of people use alfa awus.

**Comment by usama7628674** [comment]
Yes,it works on Atheros chipset but realtek chipset is not supported by hostapd.The adapter is old and outdated.Go through closed issues.

**Comment by Mehran** [comment]
yes Mine is Alfaawus036h and not worked .

**Comment by strasharo** [comment]
AWUS036H is not compatible with hostapd.

**Comment by ssrmpc** [comment]
# Everybody that is using the 8812au driver PLEASE READ THIS!

First of all I send regards to all programmers on the project. WELL DONE!

After trying everything to get AWUS036ACH to work with fluxion.... this is the conclusion for all interfaces that require the **realtek-rtl88xxau-dkms** (in my case the 8812au driver).

## Problem description
By installing apt-get install realtek-rtl88xxau-dkms you installed a driver based on [astam](https://github.com/astsam/rtl8812au) that does not correctly implement certain interfaces. Therefore this driver will never be part on the aircrack-ng project please read [THIS](https://aircrack-ng.blogspot.ch/2017/08/on-drivers-rtl8812au-wn722n-monitor.html).

Unfortunately the driver DOES NOT SUPPORT VIRTUAL INTERFACES (other than mode monitor). Therefore the fluxion fake AP created as **FXan0AP will always fail**. 

## Problem solution
If you're really after 5G Networks **YOU MUST USE 2 AWUS036ACH DEVICES**. Like that the virtual interface **FXan0AP will not be created since wlan1 is used** instead.

I tested the scenario and it works until fluxion is stopped. Unfortunately I run into another strange issue

## Another strange issue after stopping fluxion
On my Kali Linux 2017.2 running in a Parallels-Virtual machine **the network crashes in very mysterious way** so that I had to reboot.... and even the reboot had problems. 

## On my on regards
I kindly ask the responsible fluxion project manager to post my info as visible as possible. The bottomline is that the 8812au driver does not work properly! Therefore if you are new to Kali and to the wifi hacking topic **DO NOT BUY ADAPTERS USING RTL8812AU**! (Or buy two :-)

Thank you 
Marc

**Comment by flxkalu** [comment]
Thats for this information. Really helpful but are you saying that there is no way virtual interfaces would work with awus036ach at all? are you saying there is no way around it for people like us who have already bought this one??

**Comment by deltaxflux** [comment]
Well, it kind of work but I strongly recommend that you use another wireless card.

**Comment by aqeel5user** [comment]
awus036h working smoothly in wifphisher. try it.

**Comment by N1kRolexx** [comment]
Well i dont really like this way of pen. testing, cause AP you want acquire access to is ussually too far away to connect to your evil AP. But i'll check it out, thank you.

**Comment by flxkalu** [comment]
I strongly recommend awus036NHA. This adapter is so easy and straight forward. Pls do not waste your money buying the ACH adapter. Its a serious waste of money. It hardly even connects to my wireless network as big as it looks u may think it’s the best. All a lie. Stick with NHA if u want to enjoy fluxion and other hacking tools on kali.

**Comment by usama7628674** [comment]
@flxkalu It's the best one.

**Comment by rad4day** [comment]
Could we please stop digging up ancient issues to add more comments from now on? Especially if they don't add any knowlege? Thanks.

Yeah stick with the NHA it's a great device.
