### ISSUE TITLE
Need to make fake AP shows that it is with internet.

### ISSUE THREAD

**Issue by evgeniy4587** [FluxionNetwork/fluxion#248]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What is the current behaviour?
When target user trying to connect to our fake AP from phone or laptop it show a message on his/her screen( in network list it show in all OS), that AP without internet connection. I know it's ok. But is it pissible (if I have 2 or 3 wifi adapters) to make fake AP on the one of them, then connect to my AP(with internet connection) from other adapter and make some kind of bridge between them? Maybe without/with modifying fluxion script.

When target user connect to fake AP(it was in my case) he saw that AP was without internet connection and immediately disconnecting from it, even did not trying to open browser(I saw it in FAKEDNS window). I checked that fake AP with my phone it was ok, I saw the fake portal on my phone screen, entered the password(I did not know the password) in Wifi information window it show 1 client and 1 attemp(my phone). With fake AP everything was ok. I think the main reason that the target client did not go thru the whole process, was message on his phone that AP is without internet connection. 
### If this is a feature request, what is the motivation or use case for the added feature?
Make target user to believe that fake AP have internet and be less suspicious. Let him go thru all steps of process.

**Comment by MPX4132** [comment]
The problem with this is that captive portals are meant to prevent internet access. People have requested the same thing before, but it makes no sense to have an internet connection on the captive portal. If you've ever used a captive portal, you'll see they that's exactly what happens. The devices complain about no internet connection, until you input the portal's access code, in this case, the WPA PSK.

**Comment by evgeniy4587** [comment]
I know that, but what if make somehow to load firs our captive portal and reject all other sites. Maybe it is possible in fakedns.

**Comment by MPX4132** [comment]
That's what the fakedns is doing already, it's routing every request to 192.168.254.1 (the captive portal / fluxion machine).

**Comment by evgeniy4587** [comment]
Is it possible to know if target user run browser on his phone/PC? If possible we just can wait that moment and than run the fake dns. And before user run the browser maybe possible to make some tunnel between our adapters(one fake and second that connected to real AP with internet access). And hold that tunnel till target user run browser or app. Then start fake dns. Unfortunately my knowledge of coding not very well(a little bit of python) and I don't know how to realize it.

**Comment by MPX4132** [comment]
Well, we might not have to do that. Modern systems check a specific site to see if there’s a captive portal blocking passage to the internet. For example, Apple devices check “captive.apple.com” and if the device can successfully reach that site, it means there is NO captive portal. I’m sure Android phones check something with Google.

I think the reason people are getting those “connectivity errors” is because the DNS is forwarding all traffic to fluxion’s captive portal. That’s a problem because some services require a secure connection to a server, but the DNS keeps redirecting to an insecure site (fluxion’s captive portal). That leads the target clients to start showing security warnings.

I think redirecting only certain requests might fix it, while ignoring or showing a “not found” for everything else to suppress the security warnings.

**Comment by MPX4132** [comment]
I need to experiment with that idea. I haven’t experimented because I’ve been preoccupied with other issues not related to fluxion.

**Comment by evgeniy4587** [comment]
Yes it's right that  what can work for it. Just give access to secure checking services like captive.apple. I will collect info where different OS is checking connection.

**Comment by evgeniy4587** [comment]
Look on this please: https://github.com/vanhoefm/krackattacks-scripts. This script is about testing WPA2 protocol (their site and explanation about vulnerability: https://www.krackattacks.com/). But the script most important. It makes fake AP with hostapd and when I'm connecting to that AP during test I DON'T have a massage from my phone(aple) that AP is without internet connection. And when I saw video from youtube about this script, people with android phones also didn't have message about internet connection. Maybe we can use method from that script to make fake AP?

**Comment by evgeniy4587** [comment]
https://www.youtube.com/watch?v=mYtvjijATa4

**Comment by MPX4132** [comment]
I've read about the krackattacks vulnerability in the WPA2 protocol, it affects clients, not stations. They're not getting errors about disconnections because the access point is actually connected to the network. The krackattacks vulnerability is for spying on traffic between a client and a station. It's also possible to do data injection but I haven't looked into that because I've been busy.

**Comment by minanagehsalalma** [comment]
@MPX4132 @evgeniy4587 
> I think redirecting only certain requests might fix it, while ignoring or showing a “not found” for everything else to suppress the security warnings.
i agree with you it's more similar to open public wifi networks that request username and password like in cafes .. but i wonder how do it not has the security warnings problem ? (open public wifi networks)
like this [one](https://www.youtube.com/watch?v=Mka4HpJQfZM)
it works on both http and https

**Comment by evgeniy4587** [comment]
@MPX4132 Thank you for explanation, I thought it works different.

**Comment by evgeniy4587** [comment]
Why this thread was closed?

**Comment by MPX4132** [comment]
Probably because of what I explained earlier, about not needing internet. You might want to open another issue, mark it as a feature request, and explain you would like fluxion to try to prevent triggering warnings for the target clients.
