### ISSUE TITLE
Prevent triggering warnings for the target clients.

### ISSUE THREAD

**Issue by evgeniy4587** [FluxionNetwork/fluxion#252]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What is the current behaviour?
Warnings are displayed when a client of the target AP has been disconnected and attempts to connect to the fake AP (on some devices and newer versions of Android and iOS).

#### What do you think the expected behaviour should be?
The target AP clients might hesitate connecting if those warnings are present. I think Fluxion could attempt to suppress those warnings somehow. Maybe, as optional feature, filter all requests from the target client except "internet checking" addresses.

### If this is a feature request, what is the motivation or use case for the added feature?
I believe this would make fluxion more effective.

### Specs
These are some urls requested by phones right after connecting to the fake AP:

captive.apple.com 
www.apple.com
mesu.apple.com
www.icloud.com
p40-mailws.com
gsa.apple.com
query.ess.apple.com
apple.com
init-p01st.push.apple.com
gspe35-ssl.ls.apple.com
p40-keyvalueservice.icloud.com
p40-ckdatabase.icloud.com
p40.fmf.icloud.com
p40-fmip.icloud.com
lcdn-locator.apple.com
time-ios.apple.com
gs-loc.apple.com
c15.apple.com

android.clients.google.com
cdn.eyeofcloud.com
connect.rom.mini.com
connectivitycheck.gstatic.com
www.google.com
clients3.google.com
alt5-mtalk.google.com
beacons5.gvt2.com
android.clients.google.com

![apple](https://user-images.githubusercontent.com/29623145/32780222-2c961450-c949-11e7-870a-92d050447edf.png)

![android](https://user-images.githubusercontent.com/29623145/32780202-1aaf7baa-c949-11e7-811e-1ca285a66100.jpg)

**Comment by MPX4132** [comment]
I removed the part about internet, but you can add it again if you really need that. I think we might be able to solve this issue without it.

**Comment by evgeniy4587** [comment]
It's ok, does not matter will be it with or without internet. We just need to make target client open browser.

**Comment by minanagehsalalma** [comment]
@evgeniy4587  and without  showing Safety warnings at every single unsupported page

**Comment by MPX4132** [comment]
@minanagehsalalma Those safety warnings are there because the page is asking the user to send potentially sensitive data unencrypted... this can be solved by using a valid SSL certificate, which you would have to purchase from somewhere, and place it under the certificate directory in Fluxion. It’s the reason it asks you for a certificate in the first place (and people usually choose to generate one automatically, but those aren’t valid because they’re not verified by a trusted third party).

**Comment by minanagehsalalma** [comment]
@MPX4132  but how this doesn't happen with mikrotik   https://www.youtube.com/watch?v=Mka4HpJQfZM .. without buying any thing ??

**Comment by MPX4132** [comment]
@minanagehsalalma It looks like they're using some type of protocol, I'll look into it later on today.

**Comment by MPX4132** [comment]
It could also be they're not labeling their forms with something obvious like, "password," but I'm not sure. I'll check it out later.

**Comment by evgeniy4587** [comment]
I think about ssl certificates also and that's why I'm propose give it connect to original site(for example captive.apple.com). Because it will be easier to realize than get real apple\android ssl certificates.

**Comment by Hritik14** [comment]
I suppose the device just pings those IP and checks if it's successful. Maybe replying for every domain work. Perhaps using a local DNS work ?

**Comment by evgeniy4587** [comment]
I will try to make some bridge connection with two wifi adapters. Just need to figure out how target user can connect only to specified site. How to restrict all addresses on local dns server exept captive.apple.com and others.

**Comment by deltaxflux** [comment]
Well redirect the requests to your own gateway

**Comment by evgeniy4587** [comment]
Ok

**Comment by MPX4132** [comment]
I made some progress, [here's the commit](https://github.com/FluxionNetwork/fluxion/commit/54b0165db4f821993ea395714c47ff1a7ad77fc5). I'm having trouble suppressing them on Android, though. I suspect it's trying to do the checks with ssl, but I'm not sure. If that's the case, Android's out of luck. We need to look into what exactly it requires to get it to shut the hell up. I just sinked about five hours trying different things. Realistically, we'll probably have to look at the exchange it does with google with Wireshark or something.

**Comment by evgeniy4587** [comment]
[wireshark.zip](https://github.com/FluxionNetwork/fluxion/files/1523823/wireshark.zip)
I used crackatack script with testnetwork and connect to that network from apple and android phones. And sniff that connection with wireshark. You can look on it in wireshark dump-files.
Also attaching phone screen of connection without warnings.
![img_e3642](https://user-images.githubusercontent.com/29623145/33516050-83e4eb9e-d774-11e7-8be8-adc23c754722.JPG)

**Comment by minanagehsalalma** [comment]
@evgeniy4587  try the same on an open network (*-*)

**Comment by evgeniy4587** [comment]
[open-network.zip](https://github.com/FluxionNetwork/fluxion/files/1523915/open-network.zip)
it's with fluxion hostapd access point. On both target devices it shows ssl certificate warnings.

**Comment by minanagehsalalma** [comment]
can you take a look on this http://systemzone.net/mikrotik-hotspot-configuration-using-winbox/ @evgeniy4587  it may help you

**Comment by MPX4132** [comment]
@evgeniy4587 that’s convenient, thanks for the capture with wireshark. I was hoping I wouldn’t have to do it myself, lol. I think the Captive Portal has SSL warnings because it has a submittable form, and browsers don’t like sending forms unencrypted. It could also be that you’re being redirected to the https portal, which is using a self-signed certifícate and that’s a massive red flag for all browsers. I’ll check out the wire shark capture in a bit.

**Comment by MPX4132** [comment]
@minanagehsalalma Yeah, they’re suppressing the warnings by actually allowing some access to the internet. It’s not really a problem, support for that can be added. I haven’t added it because it can compromise the attacker. If a client of the target AP sends a request to an allowed url, the receiving server will have a log of traffic coming from your internet gateway.

**Comment by MPX4132** [comment]
@evgeniy4587 I can't use the capture files you posted because they're missing the interaction between Android and Google. The only useful info in the ones you gave are the DNS lookups but, even that I've already implemented into the script. I just need to know what Android is looking for when it connects to a network that has internet. If you would like to do another capture, make sure you have the access point connected to the internet. That way we can see what's going on between the two.

If you want to do it, otherwise I'll have to try doing it myself.

If you do it yourself, and want to post it, make sure you strip away all personal info in the capture.

**Comment by evgeniy4587** [comment]
I tried to make access point open in hostapd in crackatack script but looks like it don't want work without any encryption(as open).

**Comment by deltaxflux** [comment]
For me it is working without any issues. (Oreo)

**Comment by MPX4132** [comment]
@deltaxflux So you aren't getting any "no internet connection" warnings?

**Comment by deltaxflux** [comment]
Yes I don't get any internet warnings but I also could happend because I build up my own custom oreo rom.

**Comment by MPX4132** [comment]
@deltaxflux Oh okay, so you think you didn't add the connectivity checks to your custom build?

**Comment by deltaxflux** [comment]
Yeah, maybe or they work completely different in the original builds.  However, I discovered that the check do work on some networks. Do you have the same experience?

**Comment by MPX4132** [comment]
I test fluxion with my phone running the latest version of iOS. I've never experienced the warning on iOS. I had to borrow an Android phone to verify the warnings. I noticed, like @evgeniy4587 mentioned, that Android devices make contact with some of the domains he posted. I read online they always request a domain, like `client3.google.com`, or `connectivitycheck.gstatic.com`, plus the url "/response_204". That just returns a 204 response code with no content (I checked with Safari, Chrome, and Firefox). So, that's what I added to fluxion. When clients make requests to those domains, I route them to a directory with the proper response code and content, but it still shows as no internet on the device I was testing with.

The weird thing is the results I got from a capturing session I did on the Android (v6.0) device, because before I was relying on information I read from some place online. It does just like they said, it goes to those domains and receives the 204 code plus no content... That leads me to think it's doing something else to check for connectivity... It could also be manufacturer dependent, but that might not be realistic, since they would all have to implement their proprietary methods to check for connectivity. However,  I did notice the device would always communicate first with some LG server, before making any other requests right after connecting. I didn't look into it because, again, it looks like it's unfeasible to make every manufacturer write their own connectivity check. It could be some type of feature by LG, but I doubt it.

On the Apple side, we have it easy. The check iOS does is always `captive.apple.com`, so all I did was add that single domain and return what I sniffed from my phone's traffic... the response code 200 plus a body containing "Success".

**Comment by deltaxflux** [comment]
Yeah, sounds weird. However I noticed still problems with ssl sites. Unknown ssl error or something after the latest update. I can take a look at this if you want.

**Comment by MPX4132** [comment]
Yeah, if you can find out anything about those errors, that would be great. It might have to do with sites using HSTS, or something.

**Comment by minanagehsalalma** [comment]
I think The only solution is to display https so only http websites can be
opened ..

**Comment by MPX4132** [comment]
@minanagehsalalma did you mean to say we should block https and only allow http sites? What you wrote contradicts itself.

**Comment by minanagehsalalma** [comment]
Yes i meant to say block https and only allow http..  Sorry my mistake

**Comment by MPX4132** [comment]
@minanagehsalalma I suppose we can try that. Before I rewrote fluxion, the https server was disabled or it just wasn’t working. When I rewrote it I enabled listening for https, but I never noticed warnings. Then again, I was only checking with iOS.

The problem is that the site will probably still show a “not secure” warning because the captive portal has forms which could contain private data. It’s just the browser waning people it could be unsafe to submit forms because they’re sent unencrypted.

**Comment by evgeniy4587** [comment]
Is it posible to make connection by https to captive portal?

**Comment by MPX4132** [comment]
Right now, it is possible.

**Comment by evgeniy4587** [comment]
May be it will resolve ssl warnings? Try, pleasem, to rewrite fluxion in that way.

**Comment by MPX4132** [comment]
I actually did make those changes earlier, I just haven’t pushed them to the repo because I forgot lol. I disabled ssl, I’ll push it now.

**Comment by evgeniy4587** [comment]
Ok, thank you!

**Comment by MPX4132** [comment]
@evgeniy4587 Check it out, and let me know if anything changes.

**Comment by evgeniy4587** [comment]
Ok, will check it a little bit later today. Don't have my adapter right now with me :)

**Comment by MPX4132** [comment]
Thanks for the help.

**Comment by huxibei** [comment]
what are you talking about

**Comment by evgeniy4587** [comment]
see first two pictures in this post

**Comment by deltaxflux** [comment]
Yeah it use at the beginning a http server and strip all ssl site which work with most sites. However the problem with  your own ssl certificate is that it is self signed (untrustfull). However it  is also against terms and condition to use Lets Encrypt certificates.

**Comment by MPX4132** [comment]
@deltaxflux yeah, that was one of the problems about enabling ssl portals. I disabled it again to see if it fixes anything. If it doesn't we can just reenabled it.

**Comment by evgeniy4587** [comment]
Tried to test new version of fluxion. Tried it with awus036h(only airbase) and on ios it shows that network "unreliable" fnd than that it don't have internet. Today at evening will try it with other adapter with hostapd.
Also when I choose airbase method and start captive portal, the DNS-server window start for few seconds and disappear. And when I'm trying to connect to fluxion AP it cant't connect me to the AP. After 1-2 minutes fluxion AP was disappear. May be it is because I have an old adapter :) Today will try with other.

**Comment by evgeniy4587** [comment]
Checked once more with other adapter with hostapd. DNS-server window start normaly. Connected from ios, screenshots shows that it don't have warnings about no internet connection only that connection is not secured. Anfortuanetly I was failed connect from android, probably because my wifi adapter it's week laptop broadcom adapter(tried with airbase and hostapd). In general it looks better, no warning about "network without internet connection". Need someone to check it wit android.

**Comment by evgeniy4587** [comment]
![img_3648](https://user-images.githubusercontent.com/29623145/33624184-2a61a546-d9fc-11e7-8f2a-e9dff1cc4468.PNG)
![img_3649](https://user-images.githubusercontent.com/29623145/33624185-2aae30d2-d9fc-11e7-8198-d99867bf129b.PNG)

**Comment by MPX4132** [comment]
I had to undo the change for iOS devices because it was causing an issue. It was taking too long to redirect to the captive portal. The issue was caused by the fact we've disabled SSL, and most sites use it. Essentially, iOS was requesting SSL enabled sites, and was hanging because lighttpd (fluxion's web server), wasn't replying... Now, iOS immediately detects the captive portal and shows the interface.

We'll probably have to make a branch and try to work on figuring this out.

**Comment by tuthieu** [comment]
Hello there,I tested it on my android 7.1.1
After connecting to fake AP,the wifi icon show "connected,no Internet"
after few seconds,a pop-up show "Login to the network" and if I press,it'll say No internet and ask me if I keep the connection
Normally,when I don't use emulated connection,after pressing pop-up,the pop-up include captive portal show up.

**Comment by MPX4132** [comment]
@tuthieu Sorry, I’m not sure if I understood. Do you mean the emulated network connection shows as “no internet?” If that’s what you’re saying, it’s a known issue. It’s why I specified in the `Captive Portal` guide it might not work on some versions. I definitely want to fix that, but I don’t have an Android 7 device to try things with.

**Comment by tuthieu** [comment]
@MPX4132
That's what I want to say.
Thank you.

**Comment by MPX4132** [comment]
Oh ok, thanks for the report anyway.

**Comment by MPX4132** [comment]
Guys, check out the latest commit, I think I made some progress. When setting up the `Captive Portal` attack, choose to **not emulate a connection** (choose **disconnected**) and choose to **disable SSL**. It seems to affect Android 6.

**Comment by evgeniy4587** [comment]
Checked, by your instructions. Looks good. First it shows for few seconds "no internet", but then it schows as "connected". Also it chows on all sites http instead https :) but it's ok!
[Android-6.0.1.zip](https://github.com/FluxionNetwork/fluxion/files/1544605/Android-6.0.1.zip)

**Comment by MPX4132** [comment]
@evgeniy4587 Good to hear we've made some progress. You're using the latest version, right? You can now choose whether to emulate a connection, or to just leave it as disconnected, which I recommend because it triggers the captive portal prompts so the users are immediately asked to enter the key.

**Comment by evgeniy4587** [comment]
Yes, I was downloaded lust version(20 minutes ago) of fluxion and then ctart checking. I leaved it as disconnected and than start manully browser and enter addresses manualy. Also shecked it on IOS last version, and on IOS it triggers the captive portal promt immediately after phone connects to the network. On IOS also it's shows no warning, just that "network is unsecured".

**Comment by evgeniy4587** [comment]
Probably I will have possibility to check it with tthe last version of android (7) in monday.

**Comment by MPX4132** [comment]
@evgeniy4587 What version of Android are you using?

**Comment by evgeniy4587** [comment]
It's 6.0.1. I can't update it because devise is not support higher version of android.

**Comment by MPX4132** [comment]
That's strange, I tried it about an hour ago with an Android 6.X phone and it immediately took me to the captive portal after connecting. Have you tried making the phone forget the access point and then trying to connect it again?

**Comment by evgeniy4587** [comment]
Actually I tested it on my TVbox, it works on android. I'm not noticed it early, sorry for that. So it's react probably a little bit different than a usual phone.

**Comment by MPX4132** [comment]
Oh, lol, that's kinda funny. Yeah, an Android TV system will definitely behave a little differently, huh. That's okay then, you can check it out later on something else. If it doesn't work, let us know here.

**Comment by MPX4132** [comment]
Lol, I didn't even know they made Android systems for TVs. That's interesting.

**Comment by evgeniy4587** [comment]
Ok, ;)

**Comment by evgeniy4587** [comment]
MPX4132
Lol, I didn't even know they made Android systems for TVs. That's interesting.

Yes, they did it. It much more cheaper than apple tv :)

**Comment by MPX4132** [comment]
Yeah, I would imagine. The only thing I use my TV for is for playing games on the PlayStation & Xbox. I haven't used them in such a long time, though.

**Comment by tuthieu** [comment]
@MPX4132,have you tested the new captive portal with other android version?
I tested on my Android 7.1.1,the pop-up asked Login to the network(and open captive portal if I click the pop-up) instead of openning captive portal immediately like 6.0
Here's what I got on Fluxion  AP:
pyminifakeDwebconfNS:: dom.query. 60 IN A 192.168.254.1
Request: captive.apple.com. -> 192.168.254.1
Request: mtalk.google.com. -> 192.168.254.1
Request: alt5-mtalk.google.com. -> 192.168.254.1
Request: alt4-mtalk.google.com. -> 192.168.254.1
Request: www.cdn.viber.com. -> 192.168.254.1
Request: alt7-mtalk.google.com. -> 192.168.254.1
Request: clients4.google.com. -> 192.168.254.1 (repeat 10 times)
Request: www.cdn.viber.com. -> 192.168.254.1

**Comment by MPX4132** [comment]
Yeah, I think that’s correct and it’s not an issue. Some versions of android don’t do the pop up, but they do explicitly specify you must log into the network, and that’s what we want. We want that to let the users know they’re behind a wall.

**Comment by MPX4132** [comment]
I managed to test it with more devices. All modern versions of Android and iOS prompt the user with portal authentication. It seems the issue has been resolved.

**Comment by evgeniy4587** [comment]
Very big Thank You for that! It was very important enhancement. 👍 👍

**Comment by MPX4132** [comment]
@evgeniy4587 You're welcome. Yeah, it was definitely very important.
