### ISSUE TITLE
Fluxion 3.6 Captive Portal detection problem.

### ISSUE THREAD

**Issue by PASTO666** [FluxionNetwork/fluxion#295]
----the problem with rev6 is that when we connect to the clone conection.. It doesnt auto open the web browser like rev5 to input the network password :( nor doesnt say on top (android device) to click here to sign in network :( rev5 was perfect with that.. Now it doesnt on rev6 so i had to reinstall rev5

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
It’s due to the Captive Portal detection suppression that was added recently. By the way, 3.4 is fluxion 3, revision 4. We’re at fluxion 3, revision 6.

Thanks for reporting your experience. I’ll have to add an option to either enable, or disable warning suppression.

**Comment by MPX4132** [comment]
@PASTO666 I [added an option](https://github.com/FluxionNetwork/fluxion/commit/2be78a6c2d56fbf5e6a764e96891e5771bd654cc) to enable or disable that feature. Download the latest version from the repository, run the `Captive Portal` attack and when you come across the "rogue network connectivity" option, select "disconnected".

The problem was caused by a recent addition which fools Android devices into thinking internet is available. That can now be disabled by choosing not to emulate a connection.

If you have any more issues with this, or have a question about it, reply here. If you have an issue about something else, open a new issue.
