### ISSUE TITLE
Handshake detection and validation issue.

### ISSUE THREAD

**Issue by lipitb** [FluxionNetwork/fluxion#296]
There’s a network the handshake captor picks up, but the handshake isn’t being caught.
> It has a special network that the fluxion takes to find handshake and when it appears in the captor it does not detect. 

I could/did manage to get the handshake successfully with version 2.
> I managed to get the handshake with version 2. 

When I try using the hash in the latest version of fluxion, it says it’s invalid.
> Whenever using the handshake in the latest version it says hash invalid.

`.cap` file caught
> CAP anexed
<Removed to prevent doxxing>

**Comment by MPX4132** [comment]
I edited the contents of your issue because it was somewhat illegible. Please make sure what I wrote is what you were trying to say. You can try using translate.google.com to translate my sentences if that’s easier for you, and google isn’t blocked in your country.

I’m about to go to sleep because I haven’t slept all night, and I’ve already turned my computer off. I’ll verify the handshake you linked when I wake up, if no one does it before then. Sorry for making you wait.

**Comment by MPX4132** [comment]
I forgot I left my Raspberry Pi on, so I was able to check your `.cap` file with my phone:

![a14871f5-af92-49a6-92f3-8a1a0268bfc4](https://user-images.githubusercontent.com/5618628/33717022-02dcc06e-db1e-11e7-86b8-01ddb151cc4f.jpeg)

Notice the handshake file is invalid, you’ll need to recapture it. Fluxion is correct, the hash is invalid. The older version wasn’t using a reliable method of verification, which is why it was accepting bad hashes.
