### ISSUE TITLE
Raspberry Pi's internal wifi support

### ISSUE THREAD

**Issue by M1z23R** [FluxionNetwork/fluxion#299]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*feature*

#### If this is a feature request, what is the motivation or use case for the added feature?
I think it wouldn't be too hard to add export option to pre-select the desired monitor device (idea from other issue) for example export MonitorInterface=mon0; ./fluxion.sh
I also have the raspberry pi 3 and this option would be awesome with patch for broadcom integrated wifi. (It ads monitor mode support for the internal raspberry pi, but it enables monitor mode using monstart command instead of airmon).
I tried editing the script myself and managed to get it to the point where hostapd should start but maybe i am missing something, ap mode is required for wireless device and to get ap mode on raspberry pi's internal wifi but it's also not standard procedure to get to work as access point.

I hope i explained good enough since i am not that good at explaining things, in few words, i would like to add a feature to fluxion to support raspberry pi's internal wifi.
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: brcmfmac
Chipset: Unknown chipset for SDIO device.
Injection Test: socket(PF_PACKET) failed: Operation not permitted
This program requires root privileges.
failed

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm failure!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.59-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1047 SMP Sun Oct 29 12:19:23 GMT 2017

-----

**Comment by deltaxflux** [comment]
Buy a solid external wireless card. I'm not a driver developer and this issue doesn't belongs to fluxion. So I don't care.

**Comment by MPX4132** [comment]
@M1z23R It's not possible man, mainly because the device needs to do two things at once. If it's having a hard time doing monitor mode, chances are it won't be capable of master mode. You can look in the wiki to check that out, with the "Starting access point hangs" or something like that, I forgot the exact title.

**Comment by M1z23R** [comment]
I understand, but i am just trying to figure out a workaround if possible, to be honest i came for help not ask you to do the stuff for me but point in some direction :) 
I have just one more question, is monitor mode really necessary for access point (captive portal) and why ? I am not sure, but AP mode can be achieved on wifi adapters that don't support monitor mode. I know i am probably missing something but i would still like to know.

**Comment by MPX4132** [comment]
@M1z23R No, you're completely right. AP mode does not require monitor mode. The thing is, if you're using the same interface when you scan, and when you have to select the interface for the `Captive Portal` attack, then you require support for both, master mode and monitor mode.

If you're really wanna look into it, check out the InterfaceUtils.sh. Check out the `set_mode` method. It's called something like that. You could potentially overwrite that bit and see if it works for you, but we need to have a generalized version of that subroutine in fluxion, meaning no exceptions. I don't like adding exceptions to the script. If we add an exception for someone, then we have to add everyone's exceptions, it's unfair otherwise.

**Comment by M1z23R** [comment]
Oh, thank you very much again for fast response and for pointing me in the right direction, i know i am annoying but one more question, i am guessing you of all people probably know this, where exactly is hostapd called to start the AP ? I am currently working on my own "FluxionWorkaround" script that will do everything fluxion already does but the way i like it, simply put i am copypasting your python dns, dhcp, lighttpd and other coding :D

**Comment by MPX4132** [comment]
You're not annoying man, it's okay to be curious and ask questions. That's what we're here for. It's under `fluxion/lib/ap/hostapd.sh`, just modify or get what you need from the `ap_start` method at the very bottom of the script.

**Comment by M1z23R** [comment]
Thanks a lot :)
