### ISSUE TITLE
Preference Saving & Automation

### ISSUE THREAD

**Issue by Darkcast** [FluxionNetwork/fluxion#311]
First let me say thank you for this great tool I been testing it and its great for the field. 

1. It would be great if there would be a configuration file which would get save and automate some of the tasks like language, cards attack type like non sinkhole connection and monitor the traffic from the user like the kali router 

2. Create simple table that can skinable or have a script that can clone the page and add the modifications needed so it can talk to fluxion(I've been working on a couple of new sites)

**Comment by Darkcast** [comment]
3. Also have some automation like after if gets the handshake just close the window and continue to the step of the attack and not just hang in there. If there someway to automate the attack from start to finish would be awesome

**Comment by zartaz** [comment]
Guys first of all i wanna thank you for spending your precious time for all of us
i would like to propose some functions that will make the attack more realistic
1  a good idea is to create the routers fake page based on bssids mac address like airmon-ng -M
2 i think you can add the choise to install a malicious apk file or exe that extracts the saved wifi passwords from infected devices
3 a combination of the above deauth all aps in range except our free network and give internet from a malicious app

**Comment by MPX4132** [comment]
I suggest you guys check out the [wiki article](https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences) about saving preferences and automating some things. Automation is a gradual enhancement. We'll probably incorporate full automation in FLUXION 4, but that won't happen for a while. I've been pretty busy lately, and so has @deltaxflux. That's why we haven't been working on the script too much, lately.

**Comment by MPX4132** [comment]
Closed for no-reply within a week.
