### ISSUE TITLE
AP Jammer

### ISSUE THREAD

**Issue by computer00776** [FluxionNetwork/fluxion#318]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
Yes

#### What is the current behaviour?
Jammer read fail :Network down

#### What do you think the expected behaviour should be?
Periodically re-reading blaclist whitelist every 3 secs

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by computer00776** [comment]
Tried different network cards and computers with same issue
Jammer service goes down after a few minutes with
 wi_read() Network down ,
 read Failed :Network down

Thanks Guys

**Comment by zartaz** [comment]
when AP changes automatically channel its causing that error in mdk3 try that to ensure its not that the problen scan for APS choose one and see what number is the channel,run the attack till mdk3 error then scan again for aps and see if channel is changed in the ap you choose

**Comment by MPX4132** [comment]
@computer00776 It's just like @zartaz said, that occurs when the target AP changes to another channel. The other possibility is that the interface is being interrupted by another service. I'll have to close the issue because those issues aren't directly related to fluxion.

You could argue fluxion should dynamically detect changes in the target AP's channel, and I would agree, which his why we've already got that under an enhancement request. We haven't implemented that feature because the user would literally need another interface which would have to be monitoring the wireless environment. The problem with that is that most people don't have a set of wireless devices laying around which they can use all simultaneously for an attack. Some people need to run the `Captive Portal` attack with two different interfaces, imagine having a third one monitoring the environment. It's a very possible feature, but it's just not very sensible in that sense.
