### ISSUE TITLE
Router Change the Channel and Users Back and connecting ... attack Continue without effect

### ISSUE THREAD

**Issue by xXM3Do0Xx** [FluxionNetwork/fluxion#320]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
YES*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----
i used fluxion on SSID1 and Channel 11 after create the Captive Portal The WIFI back To Channel 11 And the opposite every time

**Comment by MPX4132** [comment]
I’m having a hard time understating what you mean, sorry. I believe you’re saying the target AP changes channels and the attack isn’t successful because of that.

If that’s what you mean, we’ve already got that as a known issue. I’m going to close this issue because it’s in the known issues log, we just haven’t implemented something to deal with this.

**Comment by xXM3Do0Xx** [comment]
The Target "WIFI" Change the Channel automatic 
after i selected the fake page language and wating he type the password
The Router Change The Channel from 1 to 11 and opposite  the deauth attack dont effect the target ..user back to orignal AP The same steps are repeated and the same problem occurs

**Comment by MPX4132** [comment]
@xXM3Do0Xx Yeah, it’s a known issue. There’s already [another issue open with this](https://github.com/FluxionNetwork/fluxion/issues/152), and it’s in the [known issues and improvements request](https://github.com/FluxionNetwork/fluxion/issues/294) log.
