### ISSUE TITLE
Not sure what it is 

### ISSUE THREAD

**Issue by mrpopo12** [FluxionNetwork/fluxion#344]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behavior?
when doing a captive portal attack everything seems to be fine but when several minutes have passed the jamming service screen says that the network is down i don't know what that means but it continues to do this. Does the jamming ap service has to be showing that it kicking clients out of their network or no?

#### What do you think the expected behaviour should be?
the clients have to continue to be kicked out of their own network

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
This occurs after the target access point changes channels. We haven’t implemented a fix for this because it seems like having a wireless device do three things simultaneously (be a rogue AP, jam the target AP, and monitor the regret) is impossible. We’re going to try adding a feature that lets you use another wireless device to monitor the target and dynamically change channels if it’s required.

The downside is that it requires two different wireless devices, and on some cases, where virtual interfaces aren’t supported, users will need three devices all doing their independent thing.

I’m closing the issue buecause it’s a known problem and it has already been added to the [log](https://github.com/FluxionNetwork/fluxion/issues/294). It’s known as the [dynamic deauthentication](https://github.com/FluxionNetwork/fluxion/issues/152) features.

**Comment by rodrigogs** [comment]
@MPX4132 regarding "it seems like having a wireless device do three things simultaneously (be a rogue AP, jam the target AP, and monitor the regret) is impossible", I don't think so...

I'm trying to get some time to implement it, so I can make a pull request for you. My plan is to allow user to select distinct interfaces, one to serve the captive portal and one to jam the AP(optionally). This way this attack would become a tireless killer, you could leave it running for ages!

**Comment by MPX4132** [comment]
@rodrigogs I've already implemented that functionality in Fluxion V4, so don't worry about it. You can check it out if you want, it's in the v4-development branch. I highly suggest you run it in a virtual machine. It's a development version and it's potentially unstable.

I'm warning you because when I implemented Fluxion V3, I accidentally screwed up the fluxion_exitmode function. I was about to finish implementing the script when I made that mistake and everything in my computer was deleted. I had to recover everything manually by scavenging the hard drive for script files using the `#!/bin/bash` header.

See the `# FLUXSCRIPT END` things at the bottom of the script files? They're footers, just in case I screw up again and delete all the script files. If that ever happens, I can just scavenge the hard drive using a footer and harder, which will make things much faster. You'll notice fluxion doesn't ever use rm anymore, there's only one function that has rm, and I made sure to somewhat "protect" what it can and can't do.

**Comment by rodrigogs** [comment]
Hahaha, what a mess :stuck_out_tongue:

I'm happy to know that you actually made it. I'll test it as soon as I can, then I'll give you a feedback.

**Comment by MPX4132** [comment]
Yeah, I was freaking out the whole time. Yeah, test it out. Thanks for the help, I appreciate it.

It's still under development, so there's things that still don't work or things we still haven't implemented, like target tracking.
