### ISSUE TITLE
pyrit handshake verification fails on older WPA TKIP networks (easy fix)

### ISSUE THREAD

**Issue by prlad** [FluxionNetwork/fluxion#357]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
pyrit handshake verification fails on older WPA TKIP networks, even though the handshake is correct and can be verified manually. 
This is because lib/HashUtils.sh assumes existence of AES:

`hashData=$(echo "${analysis[@]}" | awk "\$0~/#$hashID: HMAC_SHA[0-9]+_AES/{ print \$0 }")`

however, the output of `pyrit analyze` for TKIP Networks is:

> #1: AccessPoint XX:XX:XX:XX:XX:XX ('OpenWrt'):
>     #1: Station XX:XX:XX:XX:XX:XX, 2 handshake(s):
>     #1: HMAC_**_MD5_RC4_**, good, spread 1
>     #2: HMAC_**_MD5_RC4_**, good, spread 1
>   #2: Station XX:XX:XX:XX:XX:XX

#### If the current behaviour is a bug, please provide the steps to reproduce it.

Capturing WPA TKIP handshakes will reproduce this bug

#### What do you think the expected behaviour should be?

Fluxion should recognise TKIP handshakes also as follows:

`hashData=$(echo "${analysis[@]}" | awk "\$0~/#$hashID: HMAC/{ print \$0 }")`

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
Ah, thanks for the heads up. I’ll try to incorporate a fix in a bit. The development version is almost caught up with Fluxion V3’s capabilities. The biggest issue right now is that the main script, `Fluxion`,  it’s missing a method of virtual interface management. Attacks shouldn’t have to do manual management of virtual interfaces.

That means the `Captive Portal` attack doesn’t work right now because it’s lacking a secondary wireless virtual interface, just letting you know in case you tried it.

I haven’t even tried it myself. It probably crashes before getting to launching the attack.

**Comment by MPX4132** [comment]
It has been fixed in the v4-development branch, thanks for the help in narrowing it down. We appreciate it.
