### ISSUE TITLE
Captive Portal (fake Login page) doesnt work...

### ISSUE THREAD

**Issue by zer0nem0** [FluxionNetwork/fluxion#439]
Share your own router page with a simple script

cd scripts
sudo sh router.sh

i cant find "router.sh"

I have the righ usb wifi tplink...

**Comment by deltaxflux** [comment]
This has nothing todo with the captive poral. I should remove this since I removed the script.
Here is the answer I gave another user:

#### Summery

Well, debug this is pretty hard. It would be a pleasure if you could help me and share information. 

#### Debugging lighttpd
First we make sure that you submodules are installed. While beeing in the fluxion directory do:
`git submodule init && git submodule update`

This clones all required submodules. To make sure that you have all required files but the main issue here is the lighttpd or the fakedns script.We try to figure out this.

1. We check if the lighttpd is working propertly. 
2. Close the lighttpd window if any and try to run lighttpd manually
3. Use following command `lighttpd -f <conf>` 

*Note* The lighttpd config is located inside the fluxion temp directory normally in `/tmp/fluxspace`

If some strange errors appear let me know

#### Debugging fakedns
1. Run the fakedns script `python2 <script>` Located inside the fluxion temp directory.

####  Final words
Please create a new issue with all required information and I will check it out as soon as possible. 

**Edit:** I remove your screenshot because you could get doxed.
