### ISSUE TITLE
Laptop wireless card is too weak

### ISSUE THREAD

**Issue by nghtho94** [FluxionNetwork/fluxion#445]
Hello, My laptop wireless card is too weak. In AP mode, The distance (farthest) from laptop which has wireless card access point to my mobile only 2 meters. So client can not connect to my evil Twin AP. They still see original AP. 
Can anyone help me how to make wireless card stronger or another way?

I've tried :       iwconfig wlan0 txpower 30 . But it's not work.

Thank you very much.

My wireless card is : RTL8723BE

**Comment by deltaxflux** [comment]
## Short

Well, you change the power by using modifed drivers but this also limited by hardware.
There was a project https://github.com/strasharo/wifi_channel_unlocking which all this seemingly because measurements showed that this was not the case. I strongly recommend to buy a new card and read the wiki.
