### ISSUE TITLE
Realize Technology KRACK+FluxionNetwork

### ISSUE THREAD

**Issue by rdbox** [FluxionNetwork/fluxion#486]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*feature*

question to developers, I propose to implement the function of KRACK-attack.
I think it will be very cool, and I noticed that if I create an explicit KRACK script, then it will look like real. And it is not displayed with windows 7 with a yellow warning icon
What do you think ?

Technology KRACK+FluxionNetwork = Powerful HackSoft software 

-----

**Comment by MPX4132** [comment]
As far as I'm concerned, that vulnerability is used to eavesdrop on WPA2's encrypted traffic, and it's not very relevant to fluxion. At best, we could try injecting data to redirect the target user to a rogue login site, where the information may be captured, but that's not a particularly "safe" way of doing things since the target user must first visit the login page which could be traced back to the attacker.

That's not considering how reliable/unreliable data injection is with the Krack Attack exploit.

**Comment by rdbox** [comment]
You are a very competent specialist, I thought my proposal would be interesting. And now I read your answer, I realized that this does not fit.

I'm surprised at how FluxionNetwork works fine, there was no failure, it's healthy just.
FluxionNetwork for which is more suitable for tablet phone or PC?

**Comment by MPX4132** [comment]
@rdbox Thank you for your compliments, but I'm not a specialist, I just like to contribute to something on my free time. The idea of using the Krack Attack exploit isn't terrible, I'm not trying to say that, I'm just trying to say that it's very likely it would take too much time to develop and it would likely be unreliable. It's also unsafe, so that's an argument against **me** implementing it myself and wasting time.

If someone else would like to integrate the attack into fluxion somehow, I welcome it.
Again, thank you for your compliments.

**Comment by strasharo** [comment]
It's not relevant to Fluxion.
