### ISSUE TITLE
Deauth "bug" / "feature"

### ISSUE THREAD

**Issue by acocalypso** [FluxionNetwork/fluxion#511]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
deauthing clients takes too long.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
fluxl0 is on channel 1 AP is on channel 10

When I scan on one or all channels and then select an AP you should get the channel as parameter for the deauth process.

#### What do you think the expected behaviour should be?
using the channel after selecting the AP

#### If this is a feature request, what is the motivation or use case for the added feature?
faster deauthing, also it would be good to select a specific client with the -c parameter

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
@acocalypso If I had to take a guess, which I must since you didn't post the steps to reproduce the bug, **you ignored the target tracking warning tip** asking you not to select virtual interfaces and selected the same interface for it. At that point the interface is doing all three things at the same time, trying to monitor, trying to deauthenticate, and trying to channel scan (which requires channel hopping) all at the same time.

**Comment by MPX4132** [comment]
I'm closing this for no response. If you need more help or want to reopen it, go ahead, but it seems your problem is what I stated above.
