### ISSUE TITLE
Installer_utils: command not found

### ISSUE THREAD

**Issue by didotb** [FluxionNetwork/fluxion#518]
Anybody getting the same "Installer_utils_check_dependencies: command not found"
"Installer_utils_run_dependencies: command not found"
And
"sandbox_remove_workfile: command not found"?

**Comment by didotb** [comment]
Never mind it has something to do with symbolic links.
Removed the linked file and ran from the executable in the folder

**Comment by MPX4132** [comment]
Yeah, the issue is caused by the paths to the library scripts not being set correctly when called from links. You've got to call it directly from the directory. We'll have to fix that sometime, but we're likely going to make the script be "installable" so that some things, like preferences and handshakes, can be saved.

**Comment by ashiq24** [comment]
can you clearly mention how to resolve this issue? I am having the same problem.
