### ISSUE TITLE
Devices not connecting to the evil twin..

### ISSUE THREAD

**Issue by ahmad929** [FluxionNetwork/fluxion#541]
The devices are not connecting to the evil twin. I looked at the mac addresses of both the target and the cloned one. They both were different. I think so that is why the devices doesn't connect to the cloned ap after being deauthenticated.

**Comment by Gh0stInTh3M4ch1n3** [comment]
Experiencing the same. Tested on 2 phones, tablet, pi3, win10 (which shows the ap name and then a "2" after, making it less believable). The connection is too slow to connect, even on own router. Takes about 15mins at least to bring up the captive portal, continously kicks the connection and tries to reconnect. This is the issue I was going to raise. I eventually had to go to the captive portal manually using the ip it's at. Also, only the generic portals seem to work.

**Comment by MPX4132** [comment]
Read the wiki next time y’all.

**Comment by MPX4132** [comment]
The MAC address must be different, otherwise the jammer would jam the rogue AP.

Windows, being the odd ball like always, decides to add “... (2)” when it finds a duplicate AP. It’s just Windows being stupid as usual. You can verify with another device the SSID is the same as the original.

The connection is taking too long? Your device could have driver issues, but if it’s worked before chances are you’re either using airbase-ng, or didn’t read the tracker interface warning and didn’t choose “skip.”
