### ISSUE TITLE
Just keeps crashing with no results since latest update.

### ISSUE THREAD

**Issue by saintofinternet** [FluxionNetwork/fluxion#613]
since the last update things seem to have gone haywire... it just does not carry out the tasks as required and keeps crashing... just can't understand why... 

|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by rad4day** [comment]
From which version did you upgrade to 5.6? As 5.6 has only minor changes in comparison to 5.5

**Comment by saintofinternet** [comment]
not from the 5.5...i think it was a previous one... 4 i suppose... don't remember not

**Comment by usama7628674** [comment]
@saintofinternet Post the result of diagnostic script.

**Comment by the-curi0us** [comment]
In versions 5.4, 5.5 the DHCP and the MDK3 service failed because it did not deactivate the victim correctly or it did not assign an IP, but in the 5.6 it seems to be solved although sometimes it comes a moment because it is not authenticated and you have to download it fluxion again to repair that error

**Comment by minanagehsalalma** [comment]
@the-curi0us  what about #684 #618  ?! 

why this happens ?!

**Comment by strasharo** [comment]
Fixed in https://github.com/FluxionNetwork/fluxion/commit/f116e5481cf6b28805abc0688d451498e58bd7c3
