### ISSUE TITLE
UI needs a global "back" button.

### ISSUE THREAD

**Issue by scratchmex** [FluxionNetwork/fluxion#70]
### Do you want to request a *feature* or report a *bug*?
-> Feature

----

### What is the current behavior?
-> When you scan for the first time and you get the wifi list you cannot rescan as before it could be writing "r" you actually need to select random network and select back to rescan

---

#### What is the expected behavior?
-> That you can go back with "b" wherever you are 

---

**Comment by deltaxflux** [comment]
I will improve it

**Comment by MPX4132** [comment]
If all you're looking at doing is to go back, you can select a network and press back on the next menu...

**Comment by HashTagOS** [comment]
Should also provide more navigational flexibility such as **facilitate saving the network scan(s)** and **reusing previous scans**, this could also provide the ability to resume a portal attack if the information to initialize a portal was already captured in a previous scan hence saving time and providing more room for automation.

**Comment by MPX4132** [comment]
@HashTagOS that's a pretty neat idea, open a new issue with it.

**Comment by deltaxflux** [comment]
@HashTagOS @MPX4132 We had this already implemented but @MPX4132 removed it. E.g. that you use r for rescanning or b for back. Check out the earlier release. I don't have so much time to develop fluxion, sorry about that.

**Comment by MPX4132** [comment]
@deltaxflux I think @HashTagOS is talking about a "resume" feature, not the back button. For example, you could launch an attack for a couple of minutes, then you decided to stop the attack if no clients are available. After a while, you decided to relaunch the same attack as before, but instead of having to configure the attack, you select "Resume Attack" and the program starts the attack from before without having to configure it again.

**Comment by MPX4132** [comment]
I'm closing this issue since I think we've got an option to back-track just about everywhere in the script. If we want dedicated functionality, that'll have to wait till fluxion 5.
