### ISSUE TITLE
Problems with the developers of this program!!!  Ps. Don't delete it.

### ISSUE THREAD

**Issue by Pride100** [FluxionNetwork/fluxion#704]
Here is my problem!
https://youtu.be/48fr3BjMUCU
Hope u fix it as soon as possible. 

Predicted to say - YOU are ALL busy right now as ALWAYS! and ALWAYS BE TO SAY.

Correct me if I am wrong.

**Comment by Pride100** [comment]
Also wa

**Comment by Pride100** [comment]
Also watch it on HD cause predicted u will ignore it because of the bad camera.

**Comment by Pride100** [comment]
Here is the video in my pc to be clear https://youtu.be/WEFLkQM8pGg
Whopse also,
Predicted to say - YOU are ALL busy right now as ALWAYS! and ALWAYS BE TO SAY.

**Comment by rad4day** [comment]
@Pride100 I want to thank you for your invaluable and constructive contribution to the project. We really enjoyed reading this issue and I'm now more likely to watch your 4 minutes long, low quality recording of a display to fix a not closer specified bug. This seems to be a much better way of spending my time than learning for my next exams in the upcoming days.

It's not like the program is closed source. As you seem to have some time to spare, may I suggest that you may try to fix them for yourself and others, instead of raging about the developers? Alternatively you could also use another software which is not as buggy as this one is. :)
