### ISSUE TITLE
Raspberrpy Zero W

### ISSUE THREAD

**Issue by Dontmindmes** [FluxionNetwork/fluxion#747]
Is it possible to have this run on the ssh version of raspberrypi?

**Comment by strasharo** [comment]
Yes, with X forwarding to another host (ssh -X). You can't have it detached at this point, because it requires a graphical session for the xterm windows. I'm running it on RPI0W and Beaglebone Black the same way. One other issue could be the lack of memory (512mb), so you can work around that by adding an additional swap file, preferably on an external flash drive.

**Comment by sivabala21** [comment]
@strasharo I am using P4wn P1 aloa with Kali Img. I have tried to connect x11 ssh, but it still doesn't work. Please help!
