### ISSUE TITLE
./fluxion.sh command not found

### ISSUE THREAD

**Issue by LoneWolf1227** [FluxionNetwork/fluxion#804]
Hello PLEAS HELP
I using Kali Linux the latest version
I copyed fluxion today (23.November. 2019)and after making the steps cd fluxion
./fluxion.sh

I have this Error:

./fluxion.sh: line 255: format_center_literals: command not found
./fluxion.sh: line 262: format_center_literals: command not found
./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 288: installer_utils_check_dependencies: command not found
./fluxion.sh: line 289: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

After it this Error:
 ./fluxion.sh: line 375: sandbox_remove_workingfile: command not found

**Comment by Hai-cyber** [comment]
I have exactly the same problem

**Comment by deltaxflux** [comment]
Try to delete the fluxion folder and clone fluxion again.

**Comment by cjb900** [comment]
@codewithprofessor why are you post to an issue what was closed 3 years ago. You also gave no information on your setup, like what OS you are using, version of fluxion you have. So how is anyone able to try and help you.

**Comment by rafamarquesd** [comment]
> Hello PLEAS HELP I using Kali Linux the latest version I copyed fluxion today (23.November. 2019)and after making the steps cd fluxion ./fluxion.sh
> 
> I have this Error:
> 
> ./fluxion.sh: line 255: format_center_literals: command not found ./fluxion.sh: line 262: format_center_literals: command not found ./fluxion.sh: line 270: installer_utils_check_update: command not found ./fluxion.sh: line 288: installer_utils_check_dependencies: command not found ./fluxion.sh: line 289: installer_utils_run_dependencies: command not found
> 
> Dependency installation failed! Press enter to retry, ctrl+c to exit...
> 
> After it this Error: ./fluxion.sh: line 375: sandbox_remove_workingfile: command not found

I have the same problem, what is the solution?

**Comment by rafamarquesd** [comment]
> I have exactly the same problem

I have the same problem, what is the solution?

**Comment by cjb900** [comment]
@rafamarquesd So if you have the exact same issue that means you are using an over 2 year old version of Kali Linux here 🤔 Instead of posting to an old and closed issue why not open a new one with the exact details on your issue with screen shots and the exact setup you have. Then someone can try to help you. Otherwise no one is going to be able to help with what you posted here.

**Comment by darkhacknet** [comment]
holly sh..... finally I have the solution for this annoying issue... 

This can be fixed by adding it into a hidden folder.

git clone https://www.github.com/FluxionNetwork/fluxion.git ~/.fluxion
cd ~/.fluxion
sudo ./fluxion.sh -i

no w the "-i" should work, and all the dependencies will be installed sucessfully and the script will run.

**Comment by IamV1neel** [comment]
> holly sh..... finally I have the solution for this annoying issue...
> 
> This can be fixed by adding it into a hidden folder.
> 
> git clone https://www.github.com/FluxionNetwork/fluxion.git ~/.fluxion cd ~/.fluxion sudo ./fluxion.sh -i
> 
> no w the "-i" should work, and all the dependencies will be installed sucessfully and the script will run.

thanks  bud
