### ISSUE TITLE
Dependency installation failure

### ISSUE THREAD

**Issue by kandarpgautam** [FluxionNetwork/fluxion#884]
**Unable to locate package pyrit**
![Screenshot from 2020-04-23 16-14-05](https://user-images.githubusercontent.com/22766673/80090474-32ecb000-857d-11ea-8753-e3f33b53784d.png)

**system information:** 
Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

**Comment by RadhaKrishn4** [comment]
it's not an issue with github @kandarpgautam its an issue with kali pls close the thread & search for pyrit install kali 2020 in google

**Comment by cjb900** [comment]
download and install it from here [http://kali.download/kali/pool/main/p/pyrit](http://kali.download/kali/pool/main/p/pyrit)

**Comment by kandarpgautam** [comment]
Ok. I have kali Linux 2020.. it's not in official repo i think.

**Comment by kandarpgautam** [comment]
What's the name of the package? Because "sudo apt install pyrit" not working. Will i have to add a repo for it in source list?

**Comment by cjb900** [comment]
you have to install it manually from the link i posted above. there isn't any repository you can add that i know if that will let you install it with apt-get.

**Comment by kandarpgautam** [comment]
@cjb900 it would be great if fluxion could do it automatically somehow. Just like it installs other dependencies.

**Comment by cjb900** [comment]
I agree but the other dependencies it installed are still in the default repository. Its only this one that was removed in the recent kali 2020.1

**Comment by kandarpgautam** [comment]
so should i still close this issue? maintaining and providing dependencies are also necessary.

**Comment by cjb900** [comment]
¯\_(ツ)_/¯ i'm not one of the developers of this tool i can't answer that. I would assume they are aware of this issue but not sure if its something they plan on fixing or not.

**Comment by MPX4132** [comment]
If someone else can reproduce this, the issue needs to be reopened.

**Comment by cjb900** [comment]
the only dependency i know of that fails to install in the latest version of kali 2020.1 is pyrite. it was removed from the default repository in the latest kali which is why it doesn't install. If its still needed and not removed in place or cowpatty @xpz3 did make a script that will automatically checks what debian architecture like 32 or 64bit or arm and install it 
[pyrit.zip](https://github.com/FluxionNetwork/fluxion/files/4534920/pyrit.zip)

**Comment by xpz3** [comment]
The pyrit installation script was meant for debian only by downloading and installing the appropriate deb file. But there could be problems with my script when used under certain peculiar circumstances as the script uses uname instead of dpkg for determining the architecture. The download location itself is from a kali mirror which could also get removed rendering the script useless unless those files can be hosted on some git.

**Comment by strasharo** [comment]
It's not that essential to have pyrit anyway, so we can just remove it completely.

**Comment by xpz3** [comment]
> It's not that essential to have pyrit anyway, so we can just remove it completely.

@MPX4132 included pyrit, cowpatty, aircrack for verification. So maybe make pyrit an optional dependency instead of completely removing it?

**Comment by MPX4132** [comment]
Done

> > It's not that essential to have pyrit anyway, so we can just remove it completely.
> 
> @MPX4132 included pyrit, cowpatty, aircrack for verification. So maybe make pyrit an optional dependency instead of completely removing it?
