### ISSUE TITLE
Fluxion stops service even when wrong password is entered. 

### ISSUE THREAD

**Issue by aquibaj** [FluxionNetwork/fluxion#899]
Doesn't matter whether I enter a right or wrong password, fluxion saves it in a file and stops working. I tried with different handshakes, like ones captured with fluxion itself, by wifite and aerodump-ng, but all in vain. At the end, it does show if the password was correct or not on the host machine on terminal, but only after stopping the service.

**Comment by cjb900** [comment]
well it would help to know what OS you are running and what wifi adapter and chipset you have. But did you verify the hash in fluxion and create an SSL certificate. Because it doesn't crash on my end and if i enter the wrong password in the captive portal on my phone i get "Error: The password entered is incorrect!".
