### ISSUE TITLE
revolver

### ISSUE THREAD

**Issue by evoosfk** [FluxionNetwork/fluxion#924]
fatal: destination path 'revolver' already exists and is not an empty directory.
chmod: cannot access 'revolver/revolver': No such file or directory
mv: cannot stat 'revolver/revolver': No such file or directory

**Comment by cjb900** [comment]
so you make 2 separate posts and don't provide any information on what OS you are using. how you got to this error. what Wifi adapter and chipset you have. What do you expect us to do magically this information


Note: All issues will instant closed if the issue template is not complete. Please understand that it is easier for us if you fill out the template to help you faster.

!All text inside \<\!-- \--\> will be hidden from us so please remove the arrows in the statements below.


### Bug Report

#### Summary
Provide a summary desciribing the problem you are experiencing.

##### What is the current behavior?


#### How to reproduce


##### If the current behaviour is a bug, please provide the steps to reproduce it.
 A great way to do this is to provide screenshots and commands.*

##### What do you think the expected behavior should be?
What do you think should happen?

##### If this is a feature request, what is the motivation or use case for the added feature?

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### Expected behavior
 What was the expected (correct) behavior?
