### ISSUE TITLE
AP Jammer Service is not disconnecting clients

### ISSUE THREAD

**Issue by maxfouquet** [FluxionNetwork/fluxion#932]
#### Summary
I'm testing my wifi using Fluxion6.9. 
I'm using aireplay-ng to disconnect AP clients for Captive Portal attack.

##### What is the current behaviour?
AP Jammer Service displays "Waiting for beacon frames (BSSID:) on channel -1".
After 3sec, AP Jammer Service window closes. 

![Capture d’écran_2020-06-20_22-17-28](https://user-images.githubusercontent.com/16835445/85209168-06af9e80-b336-11ea-8c10-d5c24212c1e7.png)

##### If the current behaviour is a bug, please provide the steps to reproduce it.
First attack

[*] Select a wireless attack for the access point
[2] Handshake Snooper Acquires WPA/WPA2 encryption hashes.

[*] Select a wireless interface for target searching.
[1] wlan0    [-] Intel Corporation Wireless-AC 9462 

[*] Select a channel to monitor
[3] All channels (2.4GHz & 5Ghz)

[*] Select a wireless interface for target tracking.
[*] Choosing a dedicated interface may be required.
[1] wlan0    [*] Intel Corporation Wireless-AC 9462

[*] Select a method of handshake retrieval
[2] aireplay-ng deauthentication (aggressive)

[*] Select a method of verification for the hash
[2] cowpatty verification (recommended)

[*] How often should the verifier check for a handshake?
[1] Every 30 seconds (recommended).

[*] How should verification occur?
[2] Synchronously (recommended).

Second attack

[*] Fluxion is targetting the access point above.
[*] Continue with this target? [Y/n] Y

[*] Select a wireless interface for target tracking.
[*] Choosing a dedicated interface may be required.
[1] wlan0    [*] Intel Corporation Wireless-AC 9462

[*] Select a method of deauthentication
[2] aireplay

[*] Select an access point service
[1] Rogue AP - hostapd (recommended)

[*] Select a password verification method
[1] hash - cowpatty

[*] A hash for the target AP was found.
[*] Do you want to use this file?
[1] Use hash found

[*] Select a method of verification for the hash
[2] cowpatty verification (recommended)

[*] Select SSL certificate source for captive portal.
[1] Create an SSL certificate

[*] Select an internet connectivity type for the rogue network.
[1] disconnected (recommended)

[*] Select a captive portal interface for the rogue network.
[61] SFR

##### What do you think the expected behaviour should be?
- 2 wireless interfaces are required ? (I tried 1 WI for jammer & 1 WI for fake AP but stills doesn't work)
- Bad channel ?

##### Specs
Usage ./scripts/diagnostics [wireless_interface]

#### Expected behavior

AP jammer service disconnects clients properly

**Comment by maxfouquet** [comment]
Why this issue is closed ? It was resolved?

**Comment by cjb900** [comment]
your issue is most likely related to using an internal Wifi adapter. they are known to be unreliable and not properly work for wifi hacking even if they support all the modes. you are going to be better off getting USB wifi adapter that is better supported for wifi hacking like one of these. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB)

**Comment by maxfouquet** [comment]
i'm surprised because i can disconnect AP clients manually using aireplay-ng but i will try with an USB wifi adapter to work with Fluxion, thanks
