### ISSUE TITLE
32-Bit or 64-Bit.

### ISSUE THREAD

**Issue by harsh15044** [FluxionNetwork/fluxion#994]
Will Fluxion run on 32-Bit Kali Linux in Virtualbox?
Or i need 64-Bit version of Kali Linux in Virtualbox?

Please don't close the issue.!!

Please Answer...!!!!!!

**Comment by cjb900** [comment]
as long as you are able to get all the dependencies installed and working it should not matter what version of kali you use. But wifi hacking in a VM whether that's virtualbox or vmware is known to be unreliable and not always recommended.

**Comment by harsh15044** [comment]
@cjb900 Thank you so much!!!


But, i have no way other than Virtualbox, because i cant install it on myPC or Laptop

**Comment by cjb900** [comment]
i never said it wouldn't work i just said it was unreliable. You can always try it and may be it will work and you will have no issues. but with the amount of issues i've seen other have using VM's that's why i say its unreliable. Also you need to have a USB wifi adapter supports monitor mode, AP mode and VIF. if you don't have one than using a VM would not work
